### ISSUE TITLE
"skip task" annotation and/or support dnanexus native applets

### ISSUE THREAD

**Issue by jtratner** [chanzuckerberg/miniwdl#109]
On DNAnexus, you can wrap "native" applications in WDL like this:

```
task bcl2fastq220 {
    Array[File] run_archive
    File? sample_sheet
    String? advanced_opts
    command {
    }
    output {
        Array[File]+ stats = [""]
        Array[File]+ demux_summaries = [""]
        Array[File]+ fastq_summaries = [""]
        Array[File]+ reads = [""]
        Array[File] reads2 = []
        Array[File] undetermined_reads = []
        File interop_run_tar = ""
    }
    meta {
        type: "native"
        id: "applet-123"
    }
}
```

But their command section and outputs will be empty, even though all inputs are used.  Currently this will generate the following error in miniwdl

```
    task bcl2fastq220
        (Ln 437, Col 5) UnusedDeclaration, nothing references Array[File] run_archive
        (Ln 438, Col 5) UnusedDeclaration, nothing references File? sample_sheet
        (Ln 440, Col 5) UnusedDeclaration, nothing references String? advanced_opts
```

I'd like miniwdl to either auto-detect the "native" application and skip linting it for unused declarations OR allow me to leave a comment around the task to get it skipped.

**Comment by mlin** [comment]
@jtratner I added code in v0.1.5 to suppress UnusedDeclaration in such task stubs (https://github.com/chanzuckerberg/miniwdl/commit/e0ff0826f25079e195c52b479e04d2172b9d6ab7), let me know if that works out & reopen if not. Thank you for the suggestion and we really appreciate hearing about how you're using miniwdl (or even imagining it) as there are still a lot of different directions the project can go.
