### ISSUE TITLE
Task section order

### ISSUE THREAD

**Issue by mwalker174** [chanzuckerberg/miniwdl#126]
Hello,
Our WDLs (version 1.0 spec) are generating the following error:
```
(BAF.wdl) Unexpected token Token(OUTPUT, 'output') at line 369, column 3.
Expected one of:
	* CNAME
	* RUNTIME
	* COMMAND
	* RBRACE
	* INPUT
	* META_KIND
```
This corresponds to a task `output` section that precedes the `command` section. Moving `output` to after `command` fixes the error. I'm not aware of any stipulations regarding task section ordering in the spec (https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#task-definition), and all our WDLs pass `womtool validate`. 

We would like to use miniwdl but our pipeline is comprised of ~80 WDL scripts and so making this change to all tasks would be quite tedious.

**Comment by mlin** [comment]
Thanks for reporting; we can work on this. Are any of your WDLs open source? (Reason I ask -- the miniwdl test suite crawls [various open-source WDL repos](https://github.com/chanzuckerberg/miniwdl/tree/master/test_corpi) to make sure it's always able to parse them & it's always great to add more)

**Comment by mwalker174** [comment]
Thank you for your quick reply, @mlin! Unfortunately our repo is not currently open source, as it's not yet published.

**Comment by mlin** [comment]
@mwalker174 pls try v0.1.7 and let us know if there are still any related problems. Thanks!
