### ISSUE TITLE
available_inputs returns output Decls 

### ISSUE THREAD

**Issue by patmagee** [chanzuckerberg/miniwdl#135]
miniwdl version:  V0.1.7

For older workflows (ie draft 2/3) or really any workflow which does not define an `input { ... }` section, the `available_outputs` will return the `output` declarations as well as any input declarations.

For example, calling `available_outputs` on:
```wdl
workflow a {
   File in
   output {
      File out = in
   }
}
```
would yield both `in` and `out` as `inputs` to the workflow. Simply specifcying and input section for the workflow fixes this behaviour, however since alot of existing workflows do not have this section, we can expect a large number of workflows to exhibit this behaviour

**Comment by mlin** [comment]
Thanks for reporting! Quick take, `Workflow.available_inputs` relies on the helper function `_decls_and_calls` here:

https://github.com/chanzuckerberg/miniwdl/blob/ab96c3a475b04779c314a30125780c48aad86a9d/WDL/Tree.py#L739-L742

`_decls_and_calls` probably should not yield declarations in the workflow output section. 

https://github.com/chanzuckerberg/miniwdl/blob/ab96c3a475b04779c314a30125780c48aad86a9d/WDL/Tree.py#L1062-L1067

But I need to double-check nothing does assume they'll be included.
