### ISSUE TITLE
Check for unknown keys in runtime section

### ISSUE THREAD

**Issue by pshapiro4broad** [chanzuckerberg/miniwdl#150]
We ran into a case where a WDL writer used `disk` instead of `disks` in the `runtime` section. Cromwell produces a warning on startup but the warning is easy to miss. It would be nice if `miniwdl check` could check for this.

**Comment by patmagee** [comment]
@pshapiro4broad fyi https://github.com/openwdl/wdl/pull/315 This might help clarify things in the runtime

**Comment by mlin** [comment]
@pshapiro4broad thanks, this is available now in v0.2.1, and I got to file https://github.com/HumanCellAtlas/skylab/issues/225 too :smiley:
