### ISSUE TITLE
Support local cromwell JAR script and cromwell config

### ISSUE THREAD

**Issue by cmarkello** [chanzuckerberg/miniwdl#152]
@mlin
I've learned that there are different HPC systems that run cromwell differently. Though they might use the same cromwell.jar java executables they rely on different cromwell config files. This is in-part because different cromwell backends have different features depending on the batch system an HPC cluster uses to schedule jobs. What would be handy would be a way to run miniwdl providing a path to a local cromwell.jar file and cromwell config file.

Something like this:
```
CROMWELL_JAR="/path/to/local/cromwell/jar/file.jar"
CROMWELL_CONFIG="/path/to/local/cromwell/configuration/file.conf"
miniwdl cromwell -j ${CROMWELL_JAR} -c ${CROMWELL_CONFIG} hello.wdl
```

**Comment by cmarkello** [comment]
@mlin
After looking at the source code, I realize I can simply just add an optional hook to the cromwell_cmd list that specifies a path to a local config file if one is provided `-Dconfig.file=${CONFIG_FILE_PATH}`.

https://github.com/chanzuckerberg/miniwdl/blob/3b25bb55685fc25ee19535aec7ef7207d4133acb/WDL/CLI.py#L330

**Comment by cmarkello** [comment]
@mlin 
I have a remote branch ready for a pull request but I can't push the branch to this repo until I have push permissions. Could you give my push access?

**Comment by mlin** [comment]
@cmarkello sorry for the slow reply -- I've been completely buried for the last few weeks but finally opening up a bit now. Are you able to create a `cmarkello/miniwdl` fork of this repo and send a pull request with your branch pushed up to your own fork? That's a canonical github flow and shouldn't need permissions changed on anything.

**Comment by cmarkello** [comment]
@mlin no worries. I'll create a `cmarkello/miniwdl` fork and pull request against that.
I'm not extremely experienced with github, does forking the repo carry over the CI functionality?

**Comment by mlin** [comment]
@cmarkello The way it should work is *this* repo's CI will run on *your PR* when you send it. That's pretty good although it won't automatically run on *your* fork.

**Comment by prihoda** [comment]
@cmarkello 👍 

It would also be useful to look for a CROMWELL_JAR environment variable. The `--jar` argument could have higher priority over it.
