### ISSUE TITLE
Variables in the output section can not be referenced in the output section.

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#155]
The output section of the [QC pipeline in biowdl](https://github.com/biowdl/QC) looks like this:
```WDL
    output {
        File qcRead1 = if runAdapterClipping then select_first([Cutadapt.cutRead1]) else read1
        File? qcRead2 = if runAdapterClipping then Cutadapt.cutRead2 else read2
        File read1htmlReport = FastqcRead1.htmlReport
        File read1reportZip = FastqcRead1.reportZip
        File? read2htmlReport = FastqcRead2.htmlReport
        File? read2reportZip = FastqcRead2.reportZip
        File? read1afterHtmlReport = FastqcRead1After.htmlReport
        File? read1afterReportZip = FastqcRead1After.reportZip
        File? read2afterHtmlReport = FastqcRead2After.htmlReport
        File? read2afterReportZip = FastqcRead2After.reportZip
        File? cutadaptReport = Cutadapt.report
        Array[File] reports = select_all([
            read1htmlReport,
            read1reportZip,
            read2htmlReport,
            read2reportZip,
            read1afterHtmlReport,
            read1afterReportZip,
            read2afterHtmlReport,
            read2afterReportZip,
            cutadaptReport
            ])
    }
```

Where `reports` references all output. When doing miniwdl check this crashes with the following message:

```
(QC.wdl Ln 94, Col 13) Unknown identifier read1htmlReport
                read1htmlReport,
                ^^^^^^^^^^^^^^^
(QC.wdl Ln 95, Col 13) Unknown identifier read1reportZip
                read1reportZip,
                ^^^^^^^^^^^^^^
(QC.wdl Ln 96, Col 13) Unknown identifier read2htmlReport
                read2htmlReport,
                ^^^^^^^^^^^^^^^
(QC.wdl Ln 97, Col 13) Unknown identifier read2reportZip
                read2reportZip,
                ^^^^^^^^^^^^^^
(QC.wdl Ln 98, Col 13) Unknown identifier read1afterHtmlReport
                read1afterHtmlReport,
                ^^^^^^^^^^^^^^^^^^^^
(QC.wdl Ln 99, Col 13) Unknown identifier read1afterReportZip
                read1afterReportZip,
                ^^^^^^^^^^^^^^^^^^^
(QC.wdl Ln 100, Col 13) Unknown identifier read2afterHtmlReport
                read2afterHtmlReport,
                ^^^^^^^^^^^^^^^^^^^^
(QC.wdl Ln 101, Col 13) Unknown identifier read2afterReportZip
                read2afterReportZip,
                ^^^^^^^^^^^^^^^^^^^
(QC.wdl Ln 102, Col 13) Unknown identifier cutadaptReport
                cutadaptReport
                ^^^^^^^^^^^^^^
```

QC.wdl passes womtool validate and the pipeline runs fine using cromwell.

**Comment by mlin** [comment]
Thanks for reporting- this seems to be an oversight which shouldn't be difficult to take care of.

**Comment by rhpvorderman** [comment]
@mlin. Thanks! I am glad you are taking up this work of writing a WDL python parser. The linter function will be very useful for the automated testing of pipelines. We now use `womtool validate` and the pytest-workflow package to test our pipelines.

This is a very nice project and I am happy to help in any way possible. I am planning to run miniwdl on all the [biowdl](https://github.com/biowdl/) pipelines and see where there are issues. I hope to be able to fix these myself in the future, but that will require a more thorough reading of this code base.

**Comment by mlin** [comment]
@rhpvorderman thanks!! Yes, I've tried to bootstrap miniwdl+biowdl on #157 :) I can't overstate how welcome community contributions to this project will be; in fact this is one of the key metrics for its success from the sponsor's perspective.

Now that the parser/linter are fairly stable, over the summer we're building out the local WDL runner capability (you can see its beginnings in the [WDL/runtime](https://github.com/chanzuckerberg/miniwdl/tree/master/WDL/runtime) source tree, although it's far from usable yet). This could be great to hook up to pytest-workflow too.
