### ISSUE TITLE
coercion of Map literal to struct

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#172]
As mentioned: https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#using-a-struct

Example: https://github.com/biowdl/aligning/blob/75983c38d193d593e14c7b055756204f6abb1736/align-hisat2.wdl#L47

Typechecking this will be a little tricky because right now `WDL.Type.Map` doesn't keep track of the specific keys present in the map literal, just their type; but we need that information to know if the coercion is valid statically.

**Comment by patmagee** [comment]
@mlin just pointing out that the this is likely a temporaray fix until the next version of WDL, once https://github.com/openwdl/wdl/blob/6454db19d18ad4cbdbccd36ff575d7f064aa7af3/versions/development/SPEC.md#struct-literals is merged.
