### ISSUE TITLE
meta and parameter_meta cannot be used together in a workflow

### ISSUE THREAD

**Issue by patmagee** [chanzuckerberg/miniwdl#173]
There is a strange edge case with the parser that seems to prohibit `meta` and `parameter_meta` being defined within the same `workflow` section. Within a task defintion these two sections are parsed fine and allowed. This happens with all versions of WDL as well.

The following WDL is not parsed by miniwdl and produces an error:

```wdl
version 1.0
workflow a {
  input {
    String b
  }
  output {
    String c = b
  } 
  parameter_meta {
   b: "Test"
  }
  meta {
    test: "This is a test"
  }
}
```

```
(test.wdl Ln 12 Col 3) Unexpected token Token(META_KIND, 'meta') at line 12, column 3.
Expected one of: 
        * RBRACE
```

However If i remove either the `meta` or `parameter_meta` section this appears to work just fine and is properly parsed by miniwdl. I have tested this with the lastest version of MiniWDL as well as older versions and the behaviour is pretty consistent.

```wdl
version 1.0
workflow a {
  input {
    String b
  }
  output {
    String c = b
  } 
  parameter_meta {
   b: "Test"
  }
```

**Comment by mlin** [comment]
@patmagee thanks! 66752c2 should fix this in the next release
