### ISSUE TITLE
Miniwdl needs wget

### ISSUE THREAD

**Issue by nh13** [chanzuckerberg/miniwdl#191]
`wget` isn't installed by default on OSX, but is called by `miniwdl`.  

I'd suggest:
1. having `wget` stated as a pre-requisite (needed for `miniwdl cromwell`)
2. having a link in the main README to the dockerfile for example pre-requisite installs.  Currently this is hidden under the "Contributing" section in the README.

Thanks for considering this request and hopefully this helps others if they run into the same problem.

**Comment by nh13** [comment]
Added wget dependency to conda-forge's recipe too: https://github.com/conda-forge/miniwdl-feedstock/pull/5

**Comment by mlin** [comment]
Thanks -- shelling out to wget was just lazy of me. Should change to the included battery, [urlretrieve](https://docs.python.org/3.5/library/urllib.request.html#urllib.request.urlretrieve)
