### ISSUE TITLE
coerce String to Int/Float

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#198]
Is this necessary or a good idea?

https://github.com/dnanexus/dxWDL/blob/f51a2678c67b8dfff53b9a45ef643070a38a8ba4/test/basic/cast.wdl#L74-L75

**Comment by mlin** [comment]
https://github.com/HumanCellAtlas/skylab/blob/b98e88a2bfc9489700c5c286bb6038d22a0984ea/pipelines/10x/count/count.wdl#L480

https://github.com/HumanCellAtlas/skylab/blob/b98e88a2bfc9489700c5c286bb6038d22a0984ea/pipelines/10x/count/count.wdl#L735

**Comment by dinvlad** [comment]
Hi Mike,

Is that still an issue or has it been fixed in the new version? I tried to upgrade to 0.5.1, but that doesn't seem to help..

Thanks

**Comment by dinvlad** [comment]
Update: looks like a false alarm :-) The new version seems to resolve this..
