### ISSUE TITLE
attribute/method to locate `StructTypeDef` from `StructInstance`

### ISSUE THREAD

**Issue by dinvlad** [chanzuckerberg/miniwdl#223]
Hi @mlin,

As the title says, we'd like to add "Go to definition/Find references" features to all editors through LSP. In order to do that, we could either:

1) implement relevant functionality in `wdl-lsp` package, or
2) add a couple methods to MiniWDL itself.

In both cases, the methods would operate on the parsed AST, and would take a source `pos` and return a target `pos[]`, which corresponds to place(s) where it was defined/referenced.

Do you think such methods would better belong to MiniWDL, or should we implement them on our end?

Regardless, I'm thinking to approach the implementation by traversing the entire `WDL.Tree` and finding the corresponding list of `pos` : `pos[]` pairs. To improve performance, we can also construct a symbol lookup table so we only need to traverse the tree once, and do everything else in O(1), until the tree is modified.

Would be interesting to hear your thoughts.
Thanks!

CC @pshapiro4broad @rexwangcc @mohawkTrail

**Comment by dinvlad** [comment]
Thinking a little further, we'd also need a function to look up "symbol under cursor", which these features would use to look up the `WDL.SourcePosition` first.

I.e., given a `WDL.Tree.Document` and a `(src_line, src_column)` position, it should return a `WDL.SourcePosition` where `line <= src_line <= end_line` and `column <= src_column <= end_column`.

I think we can implement this search using the tree structure itself, as the most efficient 2D-range query.

Then, the remaining lookup of `WDL.SourcePosition` : `List[WDL.SourcePosition]` could still be done in O(1).

**Comment by dinvlad** [comment]
Happy to report initial success with this strategy:

<img width="230" alt="Screen Shot 2019-08-14 at 11 29 11 PM" src="https://user-images.githubusercontent.com/137337/63071022-73266980-beeb-11e9-8834-a9610cdc8d59.png">

**Comment by mlin** [comment]
The lookup table of SourcePosition to `Call`/`Ident` containing that position seems like a good idea to me. All the `Tree` and `Expr` nodes have a `children` generator that can help with the traversal. Then the documented `Call.callee` and `Ident.referee` attributes can be used to resolve the relevant `Task`/`Workflow`/`Decl` -- is that how you've already done it?

In the case of an `Ident`, there's a tricky structure if the referenced value is declared inside scatter/conditional section(s) relative to the identifier. If you find `Ident.referee` is a [`Gather`](https://miniwdl.readthedocs.io/en/latest/#WDL.Tree.Gather) node, then you can follow `Gather.final_referee` to get to the `Decl` or `Call`.

**Comment by dinvlad** [comment]
Thanks @mlin - are _all_ `SourceNode`s in a `Document` traversible through `children`, like so:
```py
def traverse(nodes: Iterable[SourceNode]):
  for node in nodes:
    traverse(node.children)
```
Or are there any `SourceNode`s that are not “reachable” this way (like any `Expr`/`Ident` perhaps)?

In other words, what constitutes a “child” of a node - are those just “direct descendants” like `input{}` in a `task{}`, or do they include `Expr` etc.?

**Comment by dinvlad** [comment]
One other thing - it appears that `Call.inputs` structure is a `Dict[str, Expr]`, which doesn't "preserve" the `SourcePosition` of its `str` keys. As a result, it's not possible to create a "link" from `s` input on line 27 to `s` input of the task on line 33:

<img width="224" alt="Screen Shot 2019-08-15 at 11 53 32 AM" src="https://user-images.githubusercontent.com/137337/63107723-781f0380-bf53-11e9-86bb-938c0b01f629.png">

**Comment by dinvlad** [comment]
Thanks a lot @mlin - I was able to follow your suggestions to find definitions/references for various nodes, incl. Gather:

https://github.com/broadinstitute/wdl-ide/blob/af7933d7094e2b9c4e15da8f7e513759ad2d1cc7/server/wdl_lsp/server.py#L182-L204

https://github.com/broadinstitute/wdl-ide/blob/af7933d7094e2b9c4e15da8f7e513759ad2d1cc7/server/wdl_lsp/server.py#L182-L204The new version of the plugins is being published right now:

**Comment by dinvlad** [comment]
Another interesting find - it doesn't currently appear possible to look up source types from inside a complex declaration, e.g.
```wdl
Array[Struct] a # (1)
```
```wdl
Array[Pair[Struct, Struct2]] a # (2)
```
Here, we might want to click on `Struct` or `Struct2` and go to their respective definitions. However, these `Decl`s only contain information about types, without an actual `SourcePosition` of each type keyword. So the best we _could_ do is handle declarations containing only up to 1 other type, like in example (1).

**Comment by mlin** [comment]
@dinvlad 

I believe the `traverse` function you showed should indeed visit each individual `Expr` and sub-expression as well as the higher-level AST nodes. Let me know if you find this not to be the case.

We do have a trade-off between convenience of the representation and not carrying through some `SourcePosition` information. For call inputs, you should be able to get `SourcePosition` from the right-hand-side `Expr` objects which are [included amongst `Call.children`](https://github.com/chanzuckerberg/miniwdl/blob/a7eabc5dd37c4fbe4ee7feb21e02bd7f69ebeb58/WDL/Tree.py#L447-L451), so it's just the outer structure of the call inputs that'd be missing. 

Although `Type` is not considered a `SourceNode`, I think it should be easy to set a `pos : Optional[SourcePosition]` attribute on the subset of `Type` objects which are instantiated by the [syntax parser](https://github.com/chanzuckerberg/miniwdl/blob/a7eabc5dd37c4fbe4ee7feb21e02bd7f69ebeb58/WDL/_parser.py#L409). However there are many other `Type` objects not created in this way (e.g. a StdLib function describing its argument & return types) so it would not always be filled in.

**Comment by dinvlad** [comment]
Thanks @mlin,

I think it's working well enough for now. I'll check with others to see if anything still needs attention.

**Comment by dinvlad** [comment]
Thanks @mlin for d9ed0b35 - that will simplify our code, because currently we rely on `node.type.type_id` for `Type.StructInstance` to access `pos`. This will be more direct and work for more types referenced through `Decl`, as you mentioned.

**Comment by mlin** [comment]
@dinvlad Great! As a heads-up, the upcoming v0.4.0 point release will contain some breaking API changes such as a rewrite of the `WDL.Env` module. I hope this will not be too disruptive for wdl-ide. I wanted to fix some nagging problems/debts before committing to API stability going forward (which we will be)

**Comment by dinvlad** [comment]
yep, we keep all dependencies strictly versioned, so it will not break any existing or new installations, and we'll just need to produce a new update for `wdl-lsp` with the fixes that use the new version of MiniWDL

**Comment by dinvlad** [comment]
Hi Mike,

I tried 0.5.1 and saw that you added `WDL.Decl.pos` for `node.type` of `WDL.Type.StructInstance` back in 0.4.0. It seems `node.type.pos` in this case is identical to `node.pos`, so we can't really use it to refer back to the definitions. It'd be nice if `node.type.pos` actually was for the underlying `StructTypeDef` (unless I misunderstood how that works..)

Thanks

**Comment by mlin** [comment]
@dinvlad Yea you are correct. I will have to noodle a bit on the right thing to do here. The complexity is that the reference might ideally traverse any number of `import` statements to get back to the original `StructTypeDef`, where it might have a totally different name too! Or perhaps in that case it should reference the `import` statement itself, which in turn would reference a `StructTypeDef` or `import` in the other document.

**Comment by dinvlad** [comment]
I see - thanks! We don't really need this per se, as I already found a workaround where I just construct the "types" map and look up the pos there, which is working great: https://github.com/broadinstitute/wdl-ide/blob/47bbb21e9fb6484be4d45806ceb44f2f76861a3b/server/wdl_lsp/server.py#L208-L209

So I think we're all set for now - don't want to over-burden your development efforts ;)

**Comment by mlin** [comment]
I just remembered how to do this while fixing some linter bugs -- updated docstring in the above commit
