### ISSUE TITLE
Document programmatic way to call miniwdl run

### ISSUE THREAD

**Issue by jdidion** [chanzuckerberg/miniwdl#231]
Currently, the only way to call miniwdl run is via the CLI. On error, the CLI method calls sys.exit, which makes it difficult to use miniwdl to execute a workflow from another library and properly handle errors.

My use case is [pytest-wdl](https://github.com/EliLillyCo/pytest-wdl). I have implemented miniwdl support but I needed to copy over most of the code from CLI.runner. I'd like to see a run method that raises an error, and CLI.runner just calls this method, traps the error, and calls sys.exit.

**Comment by mlin** [comment]
Thanks @jdidion, yea CLI.runner has too much going on in it now, we should refactor it along the lines you suggest.

**Comment by mlin** [comment]
The runner manipulates process signal handlers and soon will also set up a thread pool to run stuff concurrently/asynchronously. Something to consider about whether it makes sense to call directly within a python program (as opposed to `subprocess.check_call` out to miniwdl)

**Comment by mlin** [comment]
v0.6.0 makes progress toward this refactoring, but the documentation is still lacking. The order of ops would be something like

```
# Load the WDL document
doc = WDL.load("myworkflow.wdl")

# Typecheck the JSON-like dict of inputs against the workflow inputs
inputs_env = WDL.values_from_json(inputs_dict, doc.workflow.available_inputs, doc.workflow.required_inputs, namespace=doc.workflow.name)

# invoke runner
run_directory, outputs_env = WDL.runtime.run(doc.workflow, inputs_env)

# convert outputs to JSON-like dict
outputs_dict = WDL.values_to_json(outputs_env, namespace=doc.workflow.name)
```

**Comment by mlin** [comment]
Finally wrote https://miniwdl.readthedocs.io/en/latest/WDL.html#module-WDL.runtime
