### ISSUE TITLE
Docker error when using miniwdl to run workflow in test on Travis

### ISSUE THREAD

**Issue by jdidion** [chanzuckerberg/miniwdl#232]
I am working to add miniwdl support in pytest-wdl (branch here: https://github.com/EliLillyCo/pytest-wdl/tree/feat/38-miniwdl). One of my tests calls a workflow using both Cromwell and miniwdl. Both sub-tests pass locally, but when Travis runs them, the Cromwell test passes but the miniwdl test fails. It appears to be an issue with how miniwdl is pulling or loading the Docker image. Travis error log attached.

[miniwdl_fail.txt](https://github.com/chanzuckerberg/miniwdl/files/3569549/miniwdl_fail.txt)

**Comment by mlin** [comment]
@jdidion did the "No such image" error turn out to be some sporadic / cosmic ray problem? miniwdl effectively just calls out to `docker run` (via the docker API) so it doesn't have any specialized logic for talking to registries or pulling images.

cf. https://github.com/EliLillyCo/pytest-wdl/pull/53

**Comment by jdidion** [comment]
Nope, still not sure what's going on.

**Comment by mlin** [comment]
@jdidion So the problem is consistently reproducible?

In 40f2d22e3e98ab6fcd8c5423e0aa3c718e2c6abd I tried added a unit test using that particular image and it seemed to [pass miniwdl's own travis tests](40f2d22e3e98ab6fcd8c5423e0aa3c718e2c6abd). So I'm struggling a bit to repro/iso the issue.

**Comment by mlin** [comment]
@jdidion hope everything went well this past week; just a bump on this, is it reproducible consistently or kind of sporadic?

**Comment by jdidion** [comment]
Hi @mlin - I think this is an issue with the version of docker that comes installed on the travis instances. I am retrying after installing the latest version of docker.

Also - from what I can see from the miniwdl travis config, it is not actually running any unit tests. Your link above is now broken so I can't see the test you mean.

**Comment by jdidion** [comment]
Still no luck. 

I am seeing these two errors:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create.
...
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: frolvlad/alpine-bash:latest")
```

I can't tell which is the root cause - is pulling the image failing because the call to the Docker engine api is failing, or vice-versa? I have verified that "frolvlad/alpine-bash:latest" still works.

The docker client and python sdk are both the latest version (docker 3.0 and docker-py 4.0.2).

**Comment by mlin** [comment]
@jdidion Can you point me to a Travis run where this is occurring, I'll compare the configurations and try to close the delta? I still have not been able to repro so far.

**Comment by jdidion** [comment]
Can you see this? https://travis-ci.com/EliLillyCo/pytest-wdl/jobs/240540454

**Comment by mlin** [comment]
@jdidion Oh oh, I tried some [seemingly-inconsequential changes to the Travis config](https://github.com/chanzuckerberg/miniwdl/commit/87d18aa38acdcc351d76d38430b5f867e9d4deb1) to make it more like yours, and it [did reproduce](https://travis-ci.org/chanzuckerberg/miniwdl/jobs/591802977) the problem!

**Comment by mlin** [comment]
@jdidion I still don't understand the precise etiology in the config change, but it seems to solve the problem if I make miniwdl add the default ":latest" tag to the runtime.docker value, if no image tag is provided -- as in #246. I don't think this hurts so I'll commit that change; for now I think you can work around by adding ":latest" (or another specific tag) to that runtime.docker value. Thanks!

**Comment by jdidion** [comment]
It is very strange. When I run the test locally, even after purging all locally cached images, it still succeeds. But good to know it's just a matter of adding the tag to fix things on travis.

**Comment by mlin** [comment]
The patch to add `:latest` is effective in v0.5.0. This version has a substantial rework of the runner in order to enable (locally) parallel execution, very eager to hear how it works for you @jdidion !
