### ISSUE TITLE
`UnusedImport` even though imported struct is used

### ISSUE THREAD

**Issue by DavyCats** [chanzuckerberg/miniwdl#236]
When importing WDL files containing both tasks and structs, `miniwdl check` will report these imports as unused if only the structs get used. This might incorrectly lead people to believe that the import can be removed, even tough it is needed for the structs.

Example:
struct.wdl
```wdl
version 1.0

struct Test {
  String A
}

task TestTask {
    command {
        echo test
    }
}
```
test.wdl
```wdl
version 1.0

import "struct.wdl" as s

workflow test {
    Test A = object { A: "hey" }
}
```
output of `miniwdl check test.wdl`:
```
test.wdl
    (Ln 1, Col 1) UnusedImport, no calls to tasks/workflow in the imported document s
    workflow test
        (Ln 6, Col 5) UnusedDeclaration, nothing references struct(A : String) A
    s : struct.wdl
        task TestTask (not called)
```
The `UnusedDeclaration` is correct in this case, but `UnusedImport` might be misleading.

**Comment by mlin** [comment]
Thanks @DavyCats! yea, this was an oversight as we implemented the linter before even adding structs. Will fix
