### ISSUE TITLE
retrieve input parameters (WDL library)

### ISSUE THREAD

**Issue by KerstenBreuer** [chanzuckerberg/miniwdl#285]
Hi,

I would like to use the WDL python API to retrieve a list of input parameter (names and types) for a given workflow. The output should contain essentially the same information as ``java -jar wdltool.jar inputs myWorkflow.wdl`` would return.

Is this possible?

Thanks a lot

**Comment by KerstenBreuer** [comment]
I think I found a solution:

```
document = WDL.load('./scratch/alignment/alignment.wdl')
inputs = {}
for inp in document.workflow.available_inputs:
    inputs[f"{document.workflow.name}.{inp.name}"] = inp.value.type
```

If this is the recommended way, you may close the issue.

**Comment by mlin** [comment]
That looks good -- you could also try `WDL.values_to_json(document.workflow.available_inputs, namespace=document.workflow.name)` which should make a similar dict, but your loop is a fine general way

Only other note, `document.workflow` can be None if the document only has tasks or is empty.
