### ISSUE TITLE
generate "packed" WDL

### ISSUE THREAD

**Issue by KerstenBreuer** [chanzuckerberg/miniwdl#292]
Often I am dealing with WDL documents that import tasks from seperate files.

Is there a way to pack these workflow into one single wdl file containing all tasks using the WDL library?

Thanks a lot for your help

**Comment by mlin** [comment]
miniwdl doesn't have anything to help with this specifically yet, sorry! The general solution of making a valid packed WDL would be quite tricky because it's possible and fine for a workflow to import tasks with the same name from two different files; so the packing would need to carefully deconflict and rewrite names. Structs too.

Cromwell uses zip files as I'm sure you know, but miniwdl doesn't open automatically zip files yet -- is that something you'd like to see?

Another hypothetical 80/20 solution would be to make miniwdl read a wrapper YAML format

```
---
filename: workflow.wdl
wdl: |
    version 1.0
    import "tasks.wdl"

    workflow w {
        call tasks.hello
    }
---
filename: tasks.wdl
wdl: |
    version 1.0
    task hello {
        # ...
    }
```

This would create all sorts of temptations to pile other features into this YAML wrapper, though :sweat_smile:

**Comment by KerstenBreuer** [comment]
> miniwdl doesn't have anything to help with this specifically yet, sorry! The general solution of making a valid packed WDL would be quite tricky because it's possible and fine for a workflow to import tasks with the same name from two different files; so the packing would need to carefully deconflict and rewrite names. Structs too.
> 
> Cromwell uses zip files as I'm sure you know, but miniwdl doesn't open automatically zip files yet -- is that something you'd like to see?

OK, I see. If miniwdl could wrap up all imports into a zip this would be fanastic. We just need a way how to save workflows in a structured way and I would really like to achieve this with a python library so cromwell or womtools is not an option for me. This is the same as [here](https://github.com/chanzuckerberg/miniwdl/issues/118), right?

> Another hypothetical 80/20 solution would be to make miniwdl read a wrapper YAML format
> 
> ```
> ---
> filename: workflow.wdl
> wdl: |
>     version 1.0
>     import "tasks.wdl"
> 
>     workflow w {
>         call tasks.hello
>     }
> ---
> filename: tasks.wdl
> wdl: |
>     version 1.0
>     task hello {
>         # ...
>     }
> ```
> 
> This would create all sorts of temptations to pile other features into this YAML wrapper, though 😅

And finally, we would end up recreating CWL 😄

**Comment by mlin** [comment]
@KerstenBreuer yes, now that you got me thinking about it, it'd make a nice feature for miniwdl to routinely drop such a zip file in every run directory, "for the record."

BTW, we're currently planning the project roadmap for next year, so if you have further ideas they're really welcome! Indeed one of the key project goals here is to enable Python developers like yourself to create more ecosystem tooling around WDL.

**Comment by mlin** [comment]
Possible implementation sketch:

* in [WDL.load_async()](https://github.com/chanzuckerberg/miniwdl/blob/a0b585e7c6b3ab71b3db09171a0af16b0b392150/WDL/Tree.py#L1283) or [_parser.parse_document()](https://github.com/chanzuckerberg/miniwdl/blob/a0b585e7c6b3ab71b3db09171a0af16b0b392150/WDL/_parser.py#L796), attach the original source code as a string attribute on the `Document`
* Later, starting from the main `Document`, crawl the tree of `imports` and collect each document's source code and `doc.pos.uri`, which should contain the original relative path in the import statement.
* Use Python [`zipfile`](https://docs.python.org/3/library/zipfile.html) to put them all together, including generating a directory tree to reflect the original relative import structure as needed.
* Need some way to indicate which WDL file is the 'main' one (root of the import tree)
* Unclear how to handle if an import statement used an absolute path or one with `../`

Possibly we could handle the last two cases by piling some extra metadata into the 'comment' field available for each zip file entry.

**Comment by KerstenBreuer** [comment]
> @KerstenBreuer yes, now that you got me thinking about it, it'd make a nice feature for miniwdl to routinely drop such a zip file in every run directory, "for the record."

Yes, I agree, this would be great for documenting and reproducing any run.

> BTW, we're currently planning the project roadmap for next year, so if you have further ideas they're really welcome! Indeed one of the key project goals here is to enable Python developers like yourself to create more ecosystem tooling around WDL.

That sounds super cool. I will definitely let you know if I come up with other ideas.

**Comment by KerstenBreuer** [comment]
> Possible implementation sketch:
> 
> * in [WDL.load_async()](https://github.com/chanzuckerberg/miniwdl/blob/a0b585e7c6b3ab71b3db09171a0af16b0b392150/WDL/Tree.py#L1283) or [_parser.parse_document()](https://github.com/chanzuckerberg/miniwdl/blob/a0b585e7c6b3ab71b3db09171a0af16b0b392150/WDL/_parser.py#L796), attach the original source code as a string attribute on the `Document`
> * Later, starting from the main `Document`, crawl the tree of `imports` and collect each document's source code and `doc.pos.uri`, which should contain the original relative path in the import statement.
> * Use Python [`zipfile`](https://docs.python.org/3/library/zipfile.html) to put them all together, including generating a directory tree to reflect the original relative import structure as needed.

Sounds good. However, is it really necessary to maintain the original relative import structure? We could also just drop the imported wdl files into a zip without any nested directories (of course we need to take care of conflicting/duplicate names, however, maybe we could just use the namespace defined after ``import ... as`` as filenames). In the "root" wdl, we would then need to modify the import paths accordingly. The advantage is that we could also deal with absolute import paths.

> * Need some way to indicate which WDL file is the 'main' one (root of the import tree)

Would you like to include the main workflow wdl in the zip file? My original idea was to pack only the imports into it, so that you end up with two file like this:  
* my_workflow.wdl
* my_workflow.import.zip
But I also like the idea to zip up everything into one file.

**Comment by rhpvorderman** [comment]
Hi. What coincidence. I was not aware of this issue, but I am currently working on [wdl-packager](https://github.com/biowdl/wdl-packager) which does exactly this. The first PR is open now. Feedback is welcome!
