### ISSUE TITLE
Feature request: add --strict flag to miniwdl check.

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#315]
The miniwdl check error messages are really nice. It would be nice if a `--strict` flag was added that would sys.exit(1) the program when linting failures are detected. That way it can be used in CI and as pre-commit hook.

**Comment by mlin** [comment]
Thanks. Agree. We need a way to suppress warnings on individual lines though (#183) which in turn needs some work to decorate the object tree with original source code comments.

**Comment by mlin** [comment]
Finally, we have lint suppression comments and `--strict` in just-released v0.7.3. It will probably take a few iterations to get the suppressions to work just right for all warnings. Feedback welcome!
