### ISSUE TITLE
WDL Visualizer?

### ISSUE THREAD

**Issue by dinvlad** [chanzuckerberg/miniwdl#322]
Hi all,

I was wondering if there's place for creating a WDL visualizer extension for MiniWDL? This would be a nice addition to WDL DevTools plugins then :-) Have you explored options here, or do you think this doesn't belong to MiniWDL necessarily?

Something along the lines of https://github.com/epam/pipeline-builder, but with full WDL 1.0+ support.

I'd be happy to give a shot at implementation at the upcoming WDL Hackathon at Broad..

Thanks

**Comment by mlin** [comment]
We have a codelab on using the AST to create a crude graphviz visualization,

https://miniwdl.readthedocs.io/en/latest/wdlviz.html

and a slightly (not much) better version checked in the repo: https://github.com/chanzuckerberg/miniwdl/blob/master/examples/wdlviz.py

We probably won't have bandwidth to fully flesh this out in the near future, but would definitely welcome if someone else is able to run with it!

**Comment by mlin** [comment]
Consolidating with #311
