### ISSUE TITLE
docker folder permissions on Mac

### ISSUE THREAD

**Issue by claymcleod** [chanzuckerberg/miniwdl#324]
Hey @mlin,

I got the following error when I did `miniwdl run_self_test`: wondering if you have ever seen it before? I haven't had a chance to dive in an look, probably can do so tonight but wanted to get your thoughts if you have run into it before.

```bash
2020-01-19 16:23:47,191 miniwdl-run ERROR task hello (/var/folders/z9/7n3_5hks21s7d1bz5ppx2zqxx4ymd8/T/miniwdl_run_self_test_fvg99d4e/test.wdl Ln 17 Col 13) failed
2020-01-19 16:23:47,191 miniwdl-run ERROR RuntimeError, docker task rejected: invalid mount config for type "bind": bind source path does not exist: /var/folders/z9/7n3_5hks21s7d1bz5ppx2zqxx4ymd8/T/miniwdl_run_self_test_fvg99d4e/20200119_162345_hello_caller/write_/tmpn181hh6p
```

For the record, `docker` is configured to work with my non-root user, though I don't think that's the issue:

```bash
 cmcleod@x86_64-apple-darwin13  ~/Desktop/ngsderive  docker ps                                                                              1 ↵  7692  16:23:47
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                               NAMES
d725e8b8bd94        postgres                              "docker-entrypoint.s…"   2 months ago        Up 3 days           5432/tcp, 0.0.0.0:54320->5342/tcp   vis_postgres_1
```

**Comment by mlin** [comment]
Gotta set TMPDIR on MacOSX...we need to add a warning msg about this. See:
https://github.com/common-workflow-language/cwltool/issues/328

**Comment by claymcleod** [comment]
Great, that fixed it. I can throw together a PR, were you thinking just a docs update or an actual warning shown by the CLI (or both)?

**Comment by mlin** [comment]
I'm thinking that if `miniwdl run_self_test` fails, it should determine if (i) current platform is Mac and (ii) TMPDIR is under `/var`. If so, print a message something like "Hint: try `export TMPDIR=/tmp` prior to miniwdl; more info https://...". This should appear toward the end of the standard error log to ensure it's visible on the user's terminal.

I don't have access to a Mac right now, probably will soon but help in the meantime would definitely be appreciated!

**Comment by mlin** [comment]
Added the warning and consolidated other macOS-related issues in #145
