### ISSUE TITLE
singularity support

### ISSUE THREAD

**Issue by KerstenBreuer** [chanzuckerberg/miniwdl#326]
It would be great if MiniWDL would support singularity in addition to docker. 

Singularity has been tailored towards academic needs and is often a better solution for mutli-user infrastructure.

Are there any plans to integrate it?

**Comment by mlin** [comment]
I can't provide a timeline for this right now, but certainly agree it's desirable for the reasons you mention; and we will lay some general groundwork in the meantime. Namely, refactoring the current runner codebase for more extensibility/pluggability, and adding a capability to schedule containers on Kubernetes clusters, which might eventually dovetail with [Singularity-CRI](https://github.com/sylabs/singularity-cri) (although I haven't done any due-diligence on that at all).

**Comment by KerstenBreuer** [comment]
Thanks a lot. I am already happy, that you are considering it :)

**Comment by shouldsee** [comment]
Configuring dockerd for user is much harder than singularity! Please do consider adding such support!
