### ISSUE TITLE
s3parcp downloader plugin

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#334]

**Comment by kislyuk** [comment]
As a heads up, we will eventually want to integrate checksum/etag based LRU caching into this. In other words:

- The download process should be able to short-circuit the download if there is a cache hit in the local download cache directory
  - The cache hit could match on:
    - For the remote file, the S3 etag or metadata header containing a checksum
    - For the local file, an xattr containing same (or a local download database entry containing same)
- If there is not enough free space in the local download cache directory to complete the download, the download process should be able to delete files from that directory in LRU fashion (interface for this logic TBD/subject to discussion)

**Comment by mlin** [comment]
@kislyuk here's a strawman version to get us started, it should work with the current released miniwdl version: https://github.com/chanzuckerberg/miniwdl/tree/master/examples/download_s3parcp

you can copy those files somewhere, `pip3 install --user .` and should be good to go. `miniwdl --version` should list the plugin.

a couple of possible next steps:

1. it would benefit from having a pre-built docker image for s3parcp (that'll be maintained over time). is this planned or can we make it so?
2. right now a number of things are hard-coded in the plugin which it would be better to have configurable (other than by changing the python & reinstalling). The incipient miniwdl v0.7.x branch will incorporate a runtime configuration scheme (the distant descendant of config.js), adding which involves a [somewhat wide-ranging refactoring](https://github.com/chanzuckerberg/miniwdl/pull/338). This will also be a needed bit of the foundation for a lot of the other features we're discussing of course.

**Comment by kislyuk** [comment]
Ahh config.js, my old nemesis. I actually wrote https://github.com/kislyuk/tweak for managing this type of thing, it may or may not be useful.

Thanks, this is a great start. The plugin works as expected. I will build an ad hoc Docker image for s3parcp now, but @morsecodist can help define the long-term strategy there (TBD on the call tomorrow).

**Comment by mlin** [comment]
@kislyuk @boris-dimitrov here's an [example script](https://github.com/chanzuckerberg/miniwdl/blob/v0.7.x/examples/clean_download_cache.sh) and [test](https://github.com/chanzuckerberg/miniwdl/blob/v0.7.x/examples/clean_download_cache.t) for LRU cache eviction, based on these properties of miniwdl:

> * Miniwdl doesn’t internally manage the cache’s total storage usage; but to support such processes, it updates the access timestamp (atime) and opens a shared flock() on any cached file it’s using. The script examples/clean_download_cache.sh illustrates a process to evict the least-recently used cache files that can be exclusively flocked (the latter check needed only if the cleaner must run concurrently with workflows).

My thought is a script like this could be run by the orchestration before starting the workflow, or if necessary, could be triggered from within the s3parcp plugin before and/or after a download operation. Let me know if it seems like we're in the right zipcode
