### ISSUE TITLE
programmatically accessible info on workflow failures

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#346]
In (yet-unreleased) https://github.com/chanzuckerberg/miniwdl/commit/56449942641ae875c8d53872321108007c425fea we have miniwdl dump an "error" file in the run directory after a failure. Right now it just contains str(exn) for whatever python exception caused the workflow to fail. We should give this file a structured format conveying:

1. proximate exception class, message, run dir, and source code position
2. original exception class, message, run dir, and source code position
3. for task command failures, the exit code and location of standard error file

**Comment by kislyuk** [comment]
I'd like to clarify what I think is part of the requirements here:
- a task should be able to provide structured metadata on why it errored (an error type and reason, from an application-specific vocabulary) - for now these could be two freeform text fields
- if this metadata is found, miniwdl should pick it up and write it out along with the exit code into the structured error metadata file
- this same mechanism can be used to report errors that originate within miniwdl

**Comment by mlin** [comment]
Got it. Currently the WDL standard is lacking this kind of mechanism for rich error reporting. But it's pretty easy to do either inside or outside of miniwdl. Here is a straw man for how it could be done on the current v0.7 branch:

After a workflow failure, miniwdl leaves in the run directory an `error.json` file which, if the failure cause is a nonzero exit status from a task command, includes `cause.stderr_file` a path to the task's standard error. So we could define a convention that an error message can be communicated from the task by writing a JSON one-liner to standard error including some well-known key "wdl_error_message" just before exiting. From the caller/runner perspective, if the last line of the standard error is valid JSON with that key, the value and any other contents of the JSON can be interpreted as structured error information.

The retrieval of that information could be (i) hard-coded into miniwdl, (ii) done from a task plugin and added to the raised exception, or (iii) simply performed by outside orchestration after miniwdl exits. I will prepare an example of (iii) just to start with.

Whenever we end up with something we're happy with, it would be great to propose it as a WDL spec enhancement as it's a salient missing feature IMHO.

**Comment by kislyuk** [comment]
Agreed on all.

Related: https://github.com/dnanexus/dx-toolkit/blob/c4c46cec452e551fee534e5b37462591dff101fd/src/python/dxpy/utils/exec_utils.py#L173-L188

**Comment by mlin** [comment]
Here's the example: https://github.com/chanzuckerberg/miniwdl/blob/master/examples/run_with_custom_error.py
