### ISSUE TITLE
deprecation notice: miniwdl's cromwell subcommand

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#351]
The `miniwdl cromwell` subcommand is proposed for medium-term retirement, subject to feedback & discussion here.

Since building out miniwdl's own runtime, we haven't been able to devote much energy to this Cromwell wrapper / CLI sugar. Meanwhile, other open-source tools present similar functionality with more-active growth & maintenance, namely [oliver from St. Jude Cloud](https://github.com/stjudecloud/oliver) and [cromshell from the Broad](https://github.com/broadinstitute/cromshell). 

`miniwdl cromwell` does have one distinct advantage over the similar tools: by fully parsing the desired WDL, it knows all the inputs' data types, so it can provide instant validation of the inputs / command line arguments without involving Cromwell. As oliver is a Python project, perhaps we might be able to send the capability that way for adoption.

This notice is open for community comments & concerns, which are welcome.

**Comment by cjllanwarne** [comment]
cc @claymcleod

**Comment by claymcleod** [comment]
Thanks both 👍

**Comment by claymcleod** [comment]
> `miniwdl cromwell` does have one distinct advantage over the similar tools: by fully parsing the desired WDL, it knows all the inputs' data types, so it can provide instant validation of the inputs / command line arguments without involving Cromwell. As oliver is a Python project, perhaps we might be able to send the capability that way for adoption.

This is an interesting idea, something for us to think about @jsunny23 @a-frantz @adthrasher

**Comment by mlin** [comment]
Update: barring impassioned pleas here to to keep `miniwdl cromwell` (which would be welcome), we will probably remove it from the v0.8.x lineage which is a month or two out.
