### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by shouldsee** [chanzuckerberg/miniwdl#357]
```
$ pip3 install miniwdl 
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement miniwdl (from versions: none)
```

**Comment by shouldsee** [comment]
pypi wheel helped.

**Comment by mlin** [comment]
Thanks for the report; this message from pip is kind of infamous because it's non-specific to various possible causes:

1. PyPI server unreachable due to firewall, rate-limiting, or other network issues
2. pip version too old
3. python version too old
4. mismatch between instnalled pip and python versions

You could try wading through the output with `pip3 install -vvv miniwdl` and see if there are better clues.

more info: https://github.com/pypa/pip/issues/6526

**Comment by shouldsee** [comment]
> Thanks for the report; this message from pip is kind of infamous because it's non-specific to various possible causes:
> 
> 1. PyPI server unreachable due to firewall, rate-limiting, or other network issues
> 2. pip version too old
> 3. python version too old
> 4. mismatch between instnalled pip and python versions
> 
> You could try wading through the output with `pip3 install -vvv miniwdl` and see if there are better clues.
> 
> more info: [pypa/pip#6526](https://github.com/pypa/pip/issues/6526)

thanks for the suggestion. It was indeed a python version mismatch.

```bash
  Link requires a different Python (3.5.2 not in: '>3.6.0'): https://files.pythonhosted.org/packages/ff/a3/0f5fa4e40c050892e5538bb4df19dddad699c80e67ffc2a8ef08475df3ad/miniwdl-0.7.0.tar.gz#sha256=e76f553331c603d798f3768eccea769d134672e83eb35478c987bc1f613d5396 (from https://pypi.org/simple/miniwdl/) (requires-python:>3.6.0)
Given no hashes to check 0 links for project 'miniwdl': discarding no candidates
ERROR: Could not find a version that satisfies the requirement miniwdl (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-0dtk1ulg'
ERROR: No matching distribution found for miniwdl

```

**Comment by mlin** [comment]
Alright. If it's not feasible to upgrade the system python 3.5.2, [Miniconda](https://docs.conda.io/en/latest/miniconda.html) is a good way to set up a completely separate python installation (and miniwdl has a conda package as well as PyPI)

**Comment by shouldsee** [comment]
> Alright. If it's not feasible to upgrade the system python 3.5.2, [Miniconda](https://docs.conda.io/en/latest/miniconda.html) is a good way to set up a completely separate python installation (and miniwdl has a conda package as well as PyPI)

I hate miniconda too much for some reason... Just installed `apt-get install -y python3.6` and it worked. The only problem is miniwdl does not support sudo-less execution and it's quite a pain...

**Comment by mlin** [comment]
You should not need to sudo miniwdl so long as the invoking user has [permission to control Docker](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user) (which to be clear, indirectly provides root-like powers, at least over the file system)

**Comment by shouldsee** [comment]
@mlin I see. I was not being very clear. I wanted to install a pipeline environment from scratch without sudo as a user, but in order to use miniwdl I would have to install docker first, which is non-trivial using a root-less user, hence the whole task becomes non-trivial using a rootless user.
