### ISSUE TITLE
runtime attributes starting with "runtime" are incorrectly seen as a runtime token

### ISSUE THREAD

**Issue by DavyCats** [chanzuckerberg/miniwdl#363]
When the runtime section contains an attribute which starts with the string "runtime" (eg. "runtime_minutes"), miniwdl return an error like:
```
(test.wdl Ln 9 Col 9) Unexpected token Token(RUNTIME, 'runtime') at line 9, column 9.
Expected one of:
        * RBRACE
        * CNAME
        * COMMA
```

This only seems to happen if this runtime attribute is preceded by another runtime attribute.
The following  will cause the error:
```wdl
version 1.0
task test {
    command {}
    runtime {
        memory: "4G"
        runtime_minutes: ceil(size("a", "G") * 1 / 1)
    }
}
```

Whereas this won't:
```wdl
version 1.0
task test {
    command {}
    runtime {
        runtime_minutes: ceil(size("a", "G") * 1 / 1)
        memory: "4G"
    }
}
```

This seems like a pretty low priority issue, since there are several simple workarounds. One is shown above: simply make such a runtime attribute the first in the list. You can always just pick a different name for the attribute, as well.

**Comment by mlin** [comment]
Should be fixed in just-released v0.7.1, thanks!
