### ISSUE TITLE
can't import files named `task.wdl`

### ISSUE THREAD

**Issue by a-frantz** [chanzuckerberg/miniwdl#370]
`miniwdl` interprets the file name `task.wdl` as the keyword `task` in import statements, and errors because what it thinks is a keyword is out of place.

**Comment by mlin** [comment]
The problem isn't the filename per se, but the implied namespace called `task`, that is `import "task.wdl"` is implicitly `import "task.wdl" as task` (and then later calls would need to use the `task.` namespace). If you explicitly provide a different namespace then it should work. The error message could be better for sure.

The current [development WDL spec](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#keywords) clarifies that names shouldn't collide with language keywords, although that section was added by yours truly before which it was ambiguous.

**Comment by a-frantz** [comment]
Ah that makes perfect sense. The error message is still `Unexpected keyword` when the only statement using the word `task` is the import statement, which led me to believe `miniwdl` wasn't recognizing it as a filename. So I think a better error message would be good.

Thank you!

**Comment by mlin** [comment]
Improved this in just-released v0.7.3. Thanks!
