### ISSUE TITLE
'keys' function

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#392]
https://github.com/openwdl/wdl/pull/244

**Comment by crashfrog** [comment]
Sorry to re-raise this old issue, but I'm having trouble following the chain of events - is the `keys` function supported in miniwdl 1.11.1 or not? I'm currently getting an error that implies it is not:

```
➜  ~ miniwdl check ~/Documents/microrunqc/microrunqc.wdl
(/home/crash/Documents/microrunqc/microrunqc.wdl Ln 117 Col 26) No such function: keys
        Array[String] keys = keys(depths)
                             ^^^^^^^^^^^^
```

but the various issues around this seem to imply it was implemented.

**Comment by mlin** [comment]
Make sure your source file starts with 'version 1.1' on the first line
