### ISSUE TITLE
docs improvements for v0.7.5

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#395]
- [x] rewrite tutorial using [viral-pipelines SC2 example](https://github.com/broadinstitute/viral-pipelines/tree/master/test/input/WDL/miniwdl-local)
- [x] add top-level page for `miniwdl check` covering suppressions and pre-commit

**Comment by dpark01** [comment]
the assemble_refbased test inputs provided there are actually Ebola not SARS-CoV-2, but if it's gotta be SC2 for optics, I can try to scrounge up some minimal input data

**Comment by mlin** [comment]
@dpark01 here's a draft, comments welcome! https://github.com/chanzuckerberg/miniwdl/blob/mlin-docs-v0.7.5/docs/getting_started.md

**Comment by dpark01** [comment]
Awesome. A few quick observations:
- in my hands, I didn't need to specify `--path` at all.. miniWDL seemed smart enough to look in `../tasks/` based on the relative file import and resolve it fine. Did you find this to be necessary?
- I also didn't need to download the tarball, miniWDL seemed happy to take the github URL directly.

In my [README](https://github.com/broadinstitute/viral-pipelines#basic-execution) doc, I actually suggest this:
```
miniwdl run https://raw.githubusercontent.com/broadinstitute/viral-ngs-staging/master/pipes/WDL/workflows/assemble_refbased.wdl
```

The thrilling thing about that for me is that I can just tell people to pip3 install miniwdl (or conda install) and then run that one command to get going quickly.
