### ISSUE TITLE
post-task chown also failed

### ISSUE THREAD

**Issue by supercrow** [chanzuckerberg/miniwdl#404]
I'm run a simple task, but there has error name "post-task chown also failed"
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/34891602/86531472-30e78b80-bef4-11ea-9c5a-d469f1bd4e59.png">

my system environment is Mac OS 10.15.2
my docker engine is 19.03.8
I have exported the TMPDIR=/tmp

the stderr.txt is empty, so I can't find more message

the wdl:
```
version 1.0

task work {

    command {
        echo "1"
    }

    runtime {
        docker: "ubuntu"
    }

}

workflow sample {

    call work 

}
```

**Comment by mlin** [comment]
First the task in sample.wdl failed. Then a cleanup process miniwdl runs afterwards also failed. Possibly the two failures share a root cause. If you look in the mentioned stderr.txt file (or retry it with —verbose) is there an error message from the sample.wdl which might shed any light?
Is there anything unusual about the file system or permissions in the working directory?

**Comment by supercrow** [comment]
> First the task in sample.wdl failed. Then a cleanup process miniwdl runs afterwards also failed. Possibly the two failures share a root cause. If you look in the mentioned stderr.txt file (or retry it with —verbose) is there an error message from the sample.wdl which might shed any light? Is there anything unusual about the file system or permissions in the working directory?

thanks you reply ,the stderr.txt is empty, so I can't get some useful message from stderr.txt and verbose

I also change my user has the root permission

and when I execute "miniwdl run_sefl_test"

there has error like that:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/34891602/86563092-59c05d00-bf96-11ea-9f00-dd38a6a00f00.png">

I can run the docker run hello-world 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/34891602/86563193-870d0b00-bf96-11ea-80cb-5eebeff1c779.png">


and I change the environment variable too

<img width="302" alt="image" src="https://user-images.githubusercontent.com/34891602/86563161-7a88b280-bf96-11ea-9024-f75982f46bc1.png">

**Comment by mlin** [comment]
I'd be interested to see if there's anything useful in the trail of grey log messages from `miniwdl run_self_test` where it's talking to docker, e.g. these from a (successful) self-test

![image](https://user-images.githubusercontent.com/356550/86626067-de44b880-bf61-11ea-85e1-b2e70108c20e.png)

**Comment by mlin** [comment]
Closing as stale, but do reopen if we can help further!
