### ISSUE TITLE
More permissive requirements

### ISSUE THREAD

**Issue by TMiguelT** [chanzuckerberg/miniwdl#412]
Current I'm getting this error when installing my library, which depends on `miniwdl`:
```
ERROR: miniwdl 0.8.0 has requirement coloredlogs~=11.0, but you'll have coloredlogs 14.0 which is inc
ompatible.
```
Now, currently we have these requirements: 
https://github.com/chanzuckerberg/miniwdl/blob/5a7724fbf1cbe7bd3b4f251994c83820646ecd9d/requirements.txt#L3-L13

Good packaging practise [1](https://pipenv-fork.readthedocs.io/en/latest/advanced.html#pipfile-vs-setup-py), [2](https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires) dictates that library requirements should be as permissive/abstract as possible, to allow compatibility with other libraries. This can include an upper and lower bound, but pinning a specific version, and possibly even using `~=some_patch_version` are problematic because they severely restrict the dependencies.

I'm wondering if it might be possible to loosen the restrictions on any of these libraries, in order to make `miniwdl` easier to include as a dependency:

* `argcomplete~=1.11.0`
* `pygtail~=0.11.0`
* `coloredlogs~=11.0`
* `python-json-logger~=0.1.11`
* `lark-parser==0.9.0`

**Comment by mlin** [comment]
Thanks @TMiguelT 
@kislyuk can you give me any quick advice on what you've seen work best?
When I put the `~=` constraints it seemed like the right concept at the time for the faster-evolving packages (eg I'm less worried about regex or docker rolling out breaking changes). But it might be too restrictive particularly with coloredlogs which seems to be doing its own thing on version numbering.

**Comment by TMiguelT** [comment]
I haven't really worked out a best practise for this myself, I think it's a hard problem. My current strategy is to start with known lower bounds, based on the features you know you're using, and then leave the upper bound open, or at least permit new minor and patch versions. Then you ensure you have regular (maybe even scheduled?) builds that install the latest versions of everything, and as soon as a new release breaks your build, you can add a pin.

In any case, I had a look at the coloredlogs release notes, and while 14.0 is technically a major version, it has some very minor changes that you may not have issue with: https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-14-0-2020-02-16. The main one is that it doesn't support older Windows, pre Windows 10.  Dropping Python 3.4 support shouldn't be an issue since you're already using 3.6+.
