### ISSUE TITLE
idea: EnvString task input type to implicitly define environment variable

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#497]
Declarations in a task (excluding outputs) allow a special type `EnvString` which is `String` in all respects, but furthermore, implicitly defines a shell environment variable in the task container, with the corresponding name and value.

**Comment by patmagee** [comment]
@mlin I would be interested in seeing this as an idea in WDL :)

**Comment by mlin** [comment]
superseded by #617
