### ISSUE TITLE
Silent failure to use AWS host credentials when missing boto3

### ISSUE THREAD

**Issue by CarlosBorroto** [chanzuckerberg/miniwdl#518]
`boto3` is not an install requirement. When using `host_credentials = true` as recommended by the documentation, if the user doesn't have `boto3` installed, the current code silently fails to obtain the host credentials as it is using a broad exception catch:
https://github.com/chanzuckerberg/miniwdl/blob/97e8c7091d3f4394ecbf7622ebefcd53f37ebb21/WDL/runtime/download.py#L310-L319

It would be good to do 1 or both of these options:
1. Catch the `ImportError` exception and log about the missing package
2. Add a line in the documentation about the `boto3` requirement

I'll be happy to work on a PR implementing both options above if there is interest.

**Comment by mlin** [comment]
@CarlosBorroto good point, thanks! I pushed a small change to at least surface ImportError noisily, and clarified the docs
