### ISSUE TITLE
Running Container Testsuite fails without much info

### ISSUE THREAD

**Issue by erikbgithub** [chanzuckerberg/miniwdl#520]
Hi,

I'm excited to get started with this tool, but currently can't get the container to run.

1. I built it myself from `main` with `podman build -t miniwdl-test -f Dockerfile .`
2. Then I started it similar to the comment in the Dockerfile: `podman run -v $(pwd):/home/wdler/miniwdl:Z -v /tmp:/tmp -it miniwdl-test`
3. I had to resolve some differences between Docker and Podman [to get the mount to work properly](https://www.tutorialworks.com/podman-rootless-volumes/), but that should be fine now.
4. I expect a test suite running and giving me test results, but it just errors out the statuscode `1` in Makefile's task `check`.

I try to make it more verbose with this change:

```Diff
index e5a5ffa..2a5db0d
--- a/Makefile
+++ b/Makefile
@@ -40,7 +40,8 @@ check:
        pyre \
                --search-path stubs \
                --typeshed `python3 -c 'import sys, site, os; print(next(p for p in (os.path.join(dir,"lib/pyre_check/typeshed") for dir in (sys.prefix,site.getuserbase())) if os.path.isdir(p)))'` \
-               --show-parse-errors check
+               --show-error-traces \
+               --verbose
        pylint -j `python3 -c 'import multiprocessing as mp; print(mp.cpu_count())'` --errors-only WDL
        flake8 WDL
```

The output I get doesn't get more helpful though:

```
$ podman run -v $(pwd):/home/wdler/miniwdl:Z -v /tmp:/tmp -it miniwdl-test
make: Entering directory '/home/wdler/miniwdl'
# regression test against pyre doing nothing (issue #100)
echo "check_check: str = 42" > WDL/DELETEME_check_check.py
make check > /dev/null 2>&1 && exit 1 || exit 0
rm WDL/DELETEME_check_check.py
pyre \
	--search-path stubs \
	--typeshed `python3 -c 'import sys, site, os; print(next(p for p in (os.path.join(dir,"lib/pyre_check/typeshed") for dir in (sys.prefix,site.getuserbase())) if os.path.isdir(p)))'` \
	--show-error-traces \
	--verbose
No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
 ƛ Client exited with error code 1
Makefile:40: recipe for target 'check' failed
make: *** [check] Error 2
make: Leaving directory '/home/wdler/miniwdl'
```

Any idea what might be off or what else I might try?

**Comment by mlin** [comment]
Thanks for posting; I'm not sure exactly what's going on there, but I personally would skip `make check` for now (which runs type-checking and source linting, i.e. nice to have but not essential) and see if you run into even-bigger problems with trying to operate within podman; which I think is likely since it's never been tried to my knowledge. We'd like to support that in view of the recent changes to Docker Desktop but no set timeline on that right now :-/

**Comment by erikbgithub** [comment]
Happy to test more with you.

I think we will end up with the need for the docker socket (which I can emulate with podman.socket, but don't really like adding into the container due to the decreased security) and docker-swarm (a feature set not provided by Podman and not planned).

Current status:
```
=========== 101 failed, 72 passed, 246 warnings, 4 errors in 24.46s ============
```

As I didn't find any test logs, I summarized the `task.log` files into this gist: https://gist.github.com/erikbgithub/be8bbcef26b01d3c77890ebb714857d7

**Comment by mlin** [comment]
Thanks -- if I may invite you to explicate the motivation(s) for using podman over dockerd, that'd help us with prioritization there. Any interest in [Singularity](https://sylabs.io/singularity/)?

**Comment by erikbgithub** [comment]
Hm, no idea what Singularity is and the website isn't really using the terms I'm used to. Is it similar to Docker and Podman?

I started to use Podman because its integration with Systemd and Kubernetes. Also because it's mostly implemented by Red Hat, which makes it drastically more likely that this tool will interact well with the rest of the ecosystem and community, that there are tons of documentation and training, and that serious bugs will get fixed asap. I don't really mind if other people do other things, but if at all possible, I want to use and integrate with Podman.

**Comment by erikbgithub** [comment]
@mlin One thing I'm really curious about is why miniwdl is integrated so tightly with docker-swarm. What are the features on top of raw docker that are important and how are they used? (I have to say I have digged through part of the code but not all of it yet.)

**Comment by mlin** [comment]
Thanks, this is helpful input. I can't provide a timeline right now, but I suspect supporting podman would not be too big a delta over supporting Singularity (which is popular in certain HPC communities).

The main thing miniwdl gets from Swarm is resource-based scheduling, i.e. churning through a queue of tasks that each declare needing certain CPU and RAM resources, trying to utilize the host system as much as possible without overloading it either. Kubernetes does that too; Swarm is just convenient since it's built-in to Docker installations. And we can implement a reasonable version of it for Singularity & podman, it was just nice not to have to up until now.

**Comment by mlin** [comment]
@erikbgithub miniwdl v1.4.0 adds [a podman option](https://miniwdl.readthedocs.io/en/latest/runner_backends.html) for task container execution. It doesn't go so far as to run the entire test suite on it, but it should work for running regular workflows. I'll close this issue now but please reopen or file new ones if you have any feedback on it. Thanks!

**Comment by erikbgithub** [comment]
Thanks a lot, @mlin!
