### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by matthdsm** [chanzuckerberg/miniwdl#527]
Hi, 

I noticed in some issues and in the code miniwdl supports different backends (e.g. singularity) and plugins (e.g. for batch job support). However, I can't find any docs on these features. Could these be added?

Thanks
M

**Comment by mlin** [comment]
The Singularity and Podman runtimes are good enough for beta testing now and documented in the following link. Thanks!

https://miniwdl.readthedocs.io/en/latest/runner_backends.html
