### ISSUE TITLE
execute miniWDL in a Docker container

### ISSUE THREAD

**Issue by Melkaz** [chanzuckerberg/miniwdl#534]
Hello,

I'd like to run miniWDL itself in a Docker container.

This doesn't work as Docker cannot bind the `tmp` volume when he is called by miniWDL : 
```
docker run \
    --rm \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    python:3.9.7-buster \
    bash -c '
    pip3 install miniwdl==1.4.1
    miniwdl run_self_test
    '
```

But when mounting the `/tmp` of my host on `/tmp` on the container side, it works:
```
docker run \
    --rm \
    --volume /tmp:/tmp \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    python:3.9.7-buster \
    bash -c '
    pip3 install miniwdl==1.4.1
    miniwdl run_self_test
    '
```

I believe this is because of this docker-with-socket approach when miniWDL attempts to spin a container and bind volumes, that container is actually started by the daemon at the host level.

I'd like to use containers for miniWDL because it allows simple update everytime a new version of miniWDL comes out, but I'm open to cleaner solutions !

Thank you :)

**Comment by dpark01** [comment]
@Melkaz funny you asked... I recently asked Mike the same thing offline, and this is what he came up with:

https://gist.github.com/mlin/72a6400f0ac215aeedf6d4001a57b67b

I can confirm that I have successfully used this to run WDLs via miniwdl (with udocker as the execution backend) inside a Docker container. I've even used this to [dsub](https://github.com/DataBiosphere/dsub) lots of miniwdl jobs to GCP's PAPI service. In theory, there's nothing really stopping you from running miniwdl inside a WDL task at this point. (I have confirmed that udocker will not run inside udocker inside docker, so this only goes so deep, which is probably a good thing for everyone).

I think this is kind of funky/unsupported/experimental, but it works just fine (I kicked off over 2000 of these on PAPI yesterday).

**Comment by Melkaz** [comment]
That's cool, thanks :)
So if I understand correctly, you don't have to mount the docker socket from your host because containers are going to be spawned inside the miniWDL container ?

I'll give it a try and let you know if my house catches fire !

**Comment by dpark01** [comment]
Yes so the docker container (such as the Dockerfile in the gist above) is the space in which you execute miniwdl. That Dockerfile already sets environment variables that tell miniwdl to use udocker instead of docker. All your WDL tasks run inside udocker inside the docker -- so no mounting docker sockets because you're running udocker in userspace in the container.

No guarantees that it doesn't crash the house.

**Comment by mlin** [comment]
@Melkaz I couldn't tell exactly what you were going for in the original post, but wanted to make sure you'd seen this doc section as well. That's been there for a couple of years whereas the udocker thing is very new and not fully stabilized yet!

https://miniwdl.readthedocs.io/en/latest/runner_advanced.html#how-to-miniwdl-run-inside-a-docker-container

I think you had to mount `/tmp` because `miniwdl run_self_test` uses it for the working directory. In general you have to mount whatever the working directory is going to be (such that the host and container paths will be identical).

**Comment by Melkaz** [comment]
Hey Mike !

So the idea is to use miniWDL in a container to simplify the updating process and help other people reproduce miniWDL runs when needed.
The problem I encountered is that, as you said, we have to bind identical paths between the host and the container, so when miniWDL attempts to spin up containers for each task, it will transparently mount the volumes from the host.

The uDocker solution doesn't cut it, unfortunately, essentially because there is no caching of container-images.

Anyway, we went back to the simplest approach: install miniwdl directly on the host and deal with the updating periodically.

Thank you all for your inputs :)

**Comment by mlin** [comment]
@Melkaz 

> The problem I encountered is that, as you said, we have to bind identical paths between the host and the container, so when miniWDL attempts to spin up containers for each task, it will transparently mount the volumes from the host.

Indeed, for example [in SWIPE we just mount `/mnt` everywhere](https://github.com/chanzuckerberg/swipe/blob/955b88dea89617f67ef8c120486629ed87ef9a33/terraform/modules/swipe-sfn-batch-job/batch_job_container_properties.yml#L3-L16) and it works well. Can you elaborate on the "problem" you're hitting -- what's unsatisfactory? 

Separately, regarding udocker caching, I believe udocker does cache images on the first use; so one thing you could try is adding `udocker pull` invocations for the desired images into the Dockerfile of the "outer" miniwdl container. Then those images should be cached when you use it to run a workflow. Let me know if this does not seem to work; one possible complication (I haven't tried) is that miniwdl itself runs `udocker pull` first, so I'm not sure if that would download it again even if already cached.

**Comment by Melkaz** [comment]
Thanks for this detailed answer @mlin, I'll think about it.
