### ISSUE TITLE
unexpected keyword None

### ISSUE THREAD

**Issue by kinow** [chanzuckerberg/miniwdl#541]
Hi,

I am working on a task in `wdl-cwl-translator` to see what's required to get `select_all` translated correctly - https://github.com/common-workflow-lab/wdl-cwl-translator/pull/141#issuecomment-1023676910

I tried to create a `None` value as per the [spec](https://github.com/openwdl/wdl/blob/main/versions/development/SPEC.md#arrayx-select_allarrayx). However, running that with the latest version from PYPI gives me:

```
(venv) kinow@ranma:~/Development/python/workspace/wdl-cwl-translator$ miniwdl run wdl2cwl/tests/wdl_files/select_all.wdl 
(wdl2cwl/tests/wdl_files/select_all.wdl Ln 6 Col 38) unexpected keyword None
(venv) kinow@ranma:~/Development/python/workspace/wdl-cwl-translator$ miniwdl --version
miniwdl v1.4.3
```

Trying the same on the latest from `git` gives a similar error (`pip install -e .`):

```
(venv) kinow@ranma:~/Development/python/workspace/miniwdl$ miniwdl run ../wdl-cwl-translator/wdl2cwl/tests/wdl_files/select_all.wdl 
(../wdl-cwl-translator/wdl2cwl/tests/wdl_files/select_all.wdl Ln 6 Col 38) unexpected keyword None
            Int? maybe_four_but_is_not = None
                                         ^^^^
(venv) kinow@ranma:~/Development/python/workspace/miniwdl$ git log -n 1
commit b0f67b15e99e9ed3454c0f44c1ce9d0ba2cff60d (HEAD -> main, upstream/main, upstream/HEAD)
Author: Mike Lin <dna@mlin.net>
Date:   Mon Jan 3 12:40:32 2022 -1000

    `miniwdl eval` subcommand to test a WDL expression in isolation (#540)
```

The SPEC appears to have added that back in [2019/2020](https://github.com/openwdl/wdl/issues/209). And I saw [this issue in miniwdl from 2020](https://github.com/chanzuckerberg/miniwdl/issues/393) as well that's fixed.

Could someone check if I'm doing something wrong, or if that's not supported yet? In the meantime I'll simply leave that value blank as I believe it will be implicitly `None` too, so I can continue working on the translation for `select_all`, but it would be best if the example from the spec worked too, I think.

Thanks
Bruno

**Comment by mlin** [comment]
Can you show the source of `select_all.wdl` please? And specifically, what does it specify as the WDL language version on the first line?

**Comment by kinow** [comment]
> Can you show the source of `select_all.wdl` please?

Sure.

```wdl
workflow SelectAll {
  input {
    Int? maybe_five = 5
    Int? maybe_four_but_is_not = None
    Int? maybe_three = 3
  }
  Array[Int] fivethree = select_all([maybe_five, maybe_four_but_is_not, maybe_three])
  Boolean is_true = fivethree == [5, 3]
}
```

It was copied from the `SPEC.md` file: https://github.com/openwdl/wdl/blob/34cd5a849c3b8b89b24f422f1e7ca22656210be9/versions/development/SPEC.md#arrayx-select_allarrayx

>And specifically, what does it specify as the WDL language version on the first line?

Ah! That could be it! I did not specify a version. If I define `version 1.0`, then the error occurs.

If I specify `version 1.1`, I see another error:

```wdl
(select_all.wdl Ln 9 Col 21) Cannot compare Array[Int] and Array[Int]+
      Boolean is_true = fivethree == [5, 3]
                        ^^^^^^^^^^^^^^^^^^^
```

Does any of it help @mlin ?

Thanks!
Bruno

**Comment by mlin** [comment]
I think the WDL version flag explains the issue with `None`, which was introduced in WDL 1.1. The comparison error looks like a bug which I'll look into.

**Comment by kinow** [comment]
@mlin just synced my local copy of `miniwdl`, and re-installing in the venv, it ran successfully with the `version 1.1` statement. Will close as I think this is now fixed (feel free to re-open in case there's anything else needed for this :+1: )

Thanks!!
