### ISSUE TITLE
Example at the bottom of wdlviz.md is 404'ing

### ISSUE THREAD

**Issue by kinow** [chanzuckerberg/miniwdl#547]
I think the workflow referenced in the example [was deleted](https://github.com/gatk-workflows/gatk4-germline-snps-indels/commit/c8d0d63baa878ea4991e3108dd04e2c3bdbae6d2). Tried using <https://raw.githubusercontent.com/gatk-workflows/gatk4-germline-snps-indels/master/haplotypecaller-gvcf-gatk4.wdl> and the script still works fine :+1: so just need a different URL I guess, but not sure if the image(s) in the same folder also won't need updating.

**Comment by mlin** [comment]
Thanks! To keep the current image I just changed the github link to the last historical version before it got deleted.

**Comment by kinow** [comment]
Thanks @mlin !
