### ISSUE TITLE
How to handle custom runtime attributes?

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#587]
Hi,

When working on slurm there is a time_limit that the scheduler observes for each job. So besides cpu and memory, also time needs to be requested. The default is one hour, which is not enough for most NGS jobs. On the other hand, requesting a lot of time will affect the scheduling priority of the jobs. This naturally encourages  people to request a runtime that is sufficient rather than claiming all the possible time.

For tihs reasons all tasks in biowdl have a time_minutes estimate for the maximum time it takes to run the job. I would like to transfer that information to the scheduler. But I get these warnings:

```
2022-08-12 13:06:03.012 wdl.w:Germline.w:call-JointGenotyping.t:call-gatherVcfs ignored runtime settings :: keys: ["time_minutes"]
```

As a result the following code in miniwdl_slurm does not work:

```python3
        time_minutes = self.runtime_values.get("time_minutes", None)
        if time_minutes is not None:
            srun_args.extend(["--time", str(time_minutes)])
```

**Comment by mlin** [comment]
@rhpvorderman I got you, check this out (and also the [base class implementation](https://github.com/chanzuckerberg/miniwdl/blob/30a744877cb6c9859f36c660e08b7e4f8c297a32/WDL/runtime/task_container.py#L189) for reference)

https://github.com/miniwdl-ext/miniwdl-backend-example/blob/e38f74997d703c55b1bb498e8e07164421b14dcf/miniwdl_backend_example/docker_run.py#L63-L76

**Comment by rhpvorderman** [comment]
Haha I feel so stupid now for checking the example :man_facepalming: . Implemented it, and it works:

> Slurm invocation: srun --cpus-per-task 1 --time 5 singularity run --pwd /mnt/miniwdl_task_container/work --containall {bind statements redacted} {redacted}/testminiwdl/germline-dna/miniwdl_singularity_cache/docker___quay.io_biocontainers_fastqc_0.11.9--0.sif

Thanks Mr. Lin, you are the best!
