### ISSUE TITLE
interpret relative config paths as relative to [file_io] root is causing problems.

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#590]
I just noticed that this breaks my workflow. I had everything set up in my cfg so that miniwdl would place files in my current working directory (in `.miniwdl/call_cache` for instance). But suddenly it wants to put everything in `/.miniwdl/call_cache` which does not exist. 

This change has taken away the functionality to use  paths relative to the current working directory. This is very inconvenient. I also do not see the value add. If I wanted to add the file in an absolute directory, I could have given an absolute directory. I like to keep any caches for each project separate, which means that I now have to create a config file for every separate project, where previously this was not the case.

**Comment by mlin** [comment]
@rhpvorderman Sorry, I think you can set it to `$PWD/.miniwdl/call_cache` to get the desired behavior back. Let me know if that doesn't work. The reason for this change was to accommodate some situations in AWS where the shared filesystem mount point is different between nodes. But you're right that it's a change to a (previously undefined) behavior, I hadn't anticipated the use of relative paths there.

**Comment by mlin** [comment]
For avoidance of doubt: I mean enter exactly $PWD/.miniwdl/call_cache, as the config loader [expands environment variables](https://github.com/chanzuckerberg/miniwdl/blob/d8481a01000118eda76cbbb30df9fa5df493b86f/WDL/runtime/config.py#L337)

**Comment by rhpvorderman** [comment]
That solved it. Thanks! I probably missed that in the documentation. It is a  very unusual feature to have for ini files, but very welcome. I updated my config and all my workflows are running happily again :smiley: .
