### ISSUE TITLE
Miniwdl fails on list with optional outputs even though select_all is used

### ISSUE THREAD

**Issue by rhpvorderman** [chanzuckerberg/miniwdl#614]
See #613  that contains a minimum reproducible example.

**Comment by rhpvorderman** [comment]
Yeah, this will result in a `Array[File]` with a `None` inside because the coercion to `None` is done **after** the `select_all`. At least that is how I understand the code.

It can be easily fixed by a hacky workaround elsewhere (`if v.value is None return os.devnull`) but that would make the codebase such a mess :sweat_smile: .

**Comment by mlin** [comment]
I have a fix in #615, I think it's the right approach but still needs a bit of polishing.
