### ISSUE TITLE
Expression placeholder options like `sep` don't work

### ISSUE THREAD

**Issue by adamnovak** [chanzuckerberg/miniwdl#633]
When interpolating in a string with a placeholder in WDL 1.1, you are supposed to be able to use "options", such as `sep` to join an array into a string. See the spec at https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#-expression-placeholder-options where it specifically gives `"python script.py ~{sep=',' numbers}"` as an example of a permissible `String` expression.

This does not seem to work in MiniWDL. When I do this:

```
pip install --upgrade miniwdl==1.9.1
cat >test.wdl <<'EOF'
version 1.1
workflow test {
    input {
        Array[String] numbers = ["1", "2"]
    }
    output {
        String result = "python script.py ~{sep=',' numbers}"
    }
}
EOF
miniwdl check test.wdl
```

I get an error like this:
```
(test.wdl Ln 7 Col 48) Unexpected token Token('EQUAL', '=') at line 7, column 48.
Expected one of: 
	* "<="
	* LPAR
	* ">="
	* "||"
	* LSQB
	* LBRACE
	* MORETHAN
	* DOT
	* PLUS
	* PERCENT
	* "!="
	* LESSTHAN
	* RBRACE
	* STAR
	* SLASH
	* MINUS
	* "=="
	* "&&"
Previous tokens: [Token('CNAME', 'sep')]

            String result = "python script.py ~{sep=',' numbers}"
```

If I instead use `version 1.0` I bet a slightly different but still basically identical error:
```
(test.wdl Ln 7 Col 48) Unexpected token Token('EQUAL', '=') at line 7, column 48.
Expected one of: 
	* LSQB
	* STAR
	* MINUS
	* "||"
	* ">="
	* "&&"
	* DOT
	* MORETHAN
	* PERCENT
	* SLASH
	* LESSTHAN
	* "=="
	* LPAR
	* RBRACE
	* "!="
	* PLUS
	* "<="
Previous tokens: [Token('CNAME', 'sep')]

            String result = "python script.py ~{sep=',' numbers}"
                                                   ^
```

The code for parsing placehodler options seems to exist in the grammar:
https://github.com/chanzuckerberg/miniwdl/blob/866121ebcc2c6a0ebd254532a0b6042381d6eb84/WDL/_grammar.py#L51-L57

I'm not sure why it isn't being used, especially for version 1.0.

**Comment by adamnovak** [comment]
This is blocking the workflows at https://github.com/human-pangenomics/hpp_production_workflows from running on Toil (and MiniWDL), since those workflows use `sep=` a lot, and Toil uses MiniWDL to parse WDL.

**Comment by mlin** [comment]
@adamnovak I think it works in the `command <<< >>>` section but not other string expressions like in your example. It looks like this is vestigial because the [corresponding section in WDL 1.0 seemed to refer to command specifically](https://github.com/openwdl/wdl/blob/main/versions/1.0/SPEC.md#expression-placeholder-options). We must have missed the generalization of the language in WDL 1.1. I don't think it should be too hard to enable, but will need to look into it.

**Comment by mlin** [comment]
@adamnovak Are you OK if this works for 1.1 but not 1.0? that would be consistent with my best interpretation of the specs.

("this" being placeholder options in string expressions *outside task commands*)

**Comment by adamnovak** [comment]
I also read it as only actually being in the spec for 1.1. Cromwell supports placeholders in strings in 1.0, and will parse options like `sep`, but doesn't actually seem to respect `sep` in strings.

So a workflow that relies on `sep` working outside of commands would have to be marked as 1.1, which would make Cromwell refuse to execute it, and a workflow that uses `sep` but doesn't actually depend on it being respected should probably stop using it to not be rejected by MiniWDL as 1.0.

I'm encountering this in trying to make a workflow work cross-platform, and I think that as long as MiniWDL allows expression placeholders *without* options in strings in 1.0, I can manage it, given that Cromwell seems to ignore the options there anyway.

The only downside is that "we support expression placeholders in strings as well as in commands, but *only* if they don't use options" is a weird thing to have to communicate.
