### ISSUE TITLE
Singularity incorrect output path resolution

### ISSUE THREAD

**Issue by adthrasher** [chanzuckerberg/miniwdl#648]
I've encountered an odd issue with `miniwdl` resolving output path locations. I'm using the built-in download function (aria2c).

https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/runtime/download.py#L169-L199

I've been using the Singularity backend. I had a failure at the first attempt of the task. When the task reran, the download completed successfully and I can see from the `aria2c` output that it wrote its output to `/mnt/miniwdl_task_container/work/__out/multiqc_config.yaml` in the container. However when `miniwdl` goes to resolve that to the output using the supplied glob, it resolves to the wrong container path `output :: name: "file", value: "/mnt/miniwdl_task_container/work2/__out/multiqc_config.yaml"`. It uses the `work2` directory which is a host path. This leads to an error: `task outputs attempted to use a path outside its working directory:` from: 

https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/runtime/task_container.py#L427-L430

I can see that `miniwdl` is getting the wrong path when evaluating the expression in this block. 

https://github.com/chanzuckerberg/miniwdl/blob/1bc3776e65d3069c2e890fa73aee0c5e44861e69/WDL/runtime/task.py#L712-L729

**Comment by mlin** [comment]
Thanks @adthrasher, this turned out to be a general bug using `glob()` in a retried task (not Singularity-specific). Checked in a fix linked above

**Comment by adthrasher** [comment]
Thanks for the fix, @mlin! Great find, @a-frantz!
