### ISSUE TITLE
Unusual behavior of `Directory` types that are cast to `String` and then entered into an `Array[String]`

### ISSUE THREAD

**Issue by markjschreiber** [chanzuckerberg/miniwdl#681]
The following snippet triggers an error in miniwdl 1.10.0 and 1.11.1 (and probably others)

```
    input {
        String docker_registry
        File input_file
        String output_file
        String delimiter
        Array[String] columns_to_add
    }

    Directory dir = "s3://omics-data/100/"
    String dir_str = dir

    Array[String] values_to_add = [input_file, output_file, dir_str]
```

`WDL.Value.File invalid path: s3://omics-data/100/`. It seems like the `String` derived from the `Directory` is now being treated as a `File` which cannot have a trailing `/`

Inserting the `Directory` into the array directory directly does work.

```
workflow Main {
    input {
        String docker_registry
        File input_file
        String output_file
        String delimiter
        Array[String] columns_to_add
    }

    Directory dir = "s3://omics-data/100/"

    Array[String] values_to_add = [input_file, output_file, dir]
```

The issue isn't unique to S3 paths.

This is OK:

```
    Directory dir = "/omics-data/100"
    String dir_str = dir

    Array[String] values_to_add = [input_file, output_file, dir_str]
```

This is not OK:

```
    Directory dir = "/omics-data/100/"
    String dir_str = dir

    Array[String] values_to_add = [input_file, output_file, dir_str]
```

So the problem seems to only happen when you cast a `Directory` to a `String` **and** the directory ends with a `/`.

**Comment by mlin** [comment]
Thanks @markjschreiber, I think this is closely related to #669 which has a fix on the main branch (but not yet released)

**Comment by markjschreiber** [comment]
Thanks @mlin, it does seem to work with the code in the main branch.
