### ISSUE TITLE
programmatic access to linter results

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#78]
Debug & add a worked example to the auto-generated docs.

**Comment by mlin** [comment]
@dinvlad Here's a known-good example of accessing the lint warnings programmatically in v0.2.2: https://miniwdl.readthedocs.io/en/latest/#module-WDL.Lint

I think they will add a lot of utility to wdl-ide especially when the user has ShellCheck installed as well. Please let me know how it goes!

**Comment by dinvlad** [comment]
WOW! I've incorporated `WDL.Lint` into LSP, and it looks really good! It even correctly highlights problems within task commands (I assume using ShellCheck?). Amazing!

We did find that `descend_imports=False` is necessary, both to improve latency of lint reporting, and to get rid of problems from another file highlighted in the current file (which only makes it confusing).

I only wonder now if it's possible to "disable" some warnings using a comment (like it's done in other languages), e.g. we have a case where we assign `File referenceFasta = referenceUri + ".fasta"`, i.e. `File <- String`. Or we have an `input { File fasta ... File amb }`, where it reports that nothing references `File amb`, even though we know that Cromwell still localizes it (which is why we declared it). I guess we can just ignore these warnings, but it would be a nice-to-have with a comment like `// miniwdl:linter-off` to ignore an affected line completely.

^ @rexwangcc @mohawkTrail

**Comment by mlin** [comment]
Great!! We'll start working on #177 soon, but I'd really like to encourage you to make some "MVP" of wdl-ide available ASARP. I'm excited to try it out myself and have a lot of other folks try it too!

Yea, `WDL.Lint` runs ShellCheck on the task command and then maps the line/column numbers back onto the WDL document. We have to ask the user to install ShellCheck themselves though since it's GPL. If it's not installed then the ShellCheck warnings will just be silently absent.

We'll certainly need the usual mechanisms to suppress specific lint warnings, but haven't gotten to that yet; I filed #183 to track it. Re the two specific cases you mentioned:
1. I know this kind of pattern `File referenceFasta = referenceUri + ".fasta"` typically works with Cromwell/GCS, but I think it legitimately deserves a warning. Allowing it means the task has to be able to access host/cloud file(s) which the launching user did not explicitly specify as inputs, which tends to invite portability/security problems. This comes up in the OpenWDL forum from time to time.
2. The UnusedDeclaration linter has a hard-coded heuristic to suppress itself if the filename suffix suggests it's an index/secondary file. Is 'amb' a common one we should add?

https://github.com/chanzuckerberg/miniwdl/blob/ed94f5ea1c9727683abce89f99be8c0adaf2f5be/WDL/Lint.py#L666-L683

**Comment by dinvlad** [comment]
> Great!! We'll start working on #177 soon, but I'd really like to encourage you to make some "MVP" of wdl-ide available ASARP. I'm excited to try it out myself and have a lot of other folks try it too!

Yep, I'm publishing the server as a PyPI package, and client as a VSCode extension, today/tomorrow. It doesn't contain any tests yet (and Cromwell submission functionality is not fully working yet), but at least that should get you started and provide some early feedback. The validation seems to work great so far. I'll update you once they're published.

I'm also hoping to publish an IntelliJ client soon, as a significant (majority?) of Broad users rely on that for their WDL development, and I believe even at this early stage the LSP plugin already provides better feedback, thanks to MiniWDL!

> We have to ask the user to install ShellCheck themselves though since it's GPL

I'll need to think what to do about ShellCheck - ideally we'd want it to be installed automatically (which is not the same as inability to distribute it ourselves!).

> I know this kind of pattern File referenceFasta = referenceUri + ".fasta" typically works with Cromwell/GCS, but I think it legitimately deserves a warning

I agree the warnings display legitimate concern in `File <- String`. I'm just asking if it would be possible to suppress it when "we know what we're doing" :)

> The UnusedDeclaration linter has a hard-coded heuristic to suppress itself if the filename suffix suggests it's an index/secondary file. Is 'amb' a common one we should add?

It may be useful to add `.amb` and other reference sequence extensions to ignore list. For our `hg19` genome, we got `.amb`, `.ann`, `.bwt`, `.pac`, and `.sa`. But I'm a bit worried about a blanket ignore, in cases where a workflow could pass and use those files explicitly.

**Comment by dinvlad** [comment]
I think for ShellCheck, we can add a config variable `wdl.shellCheckPath` (equal to `shellcheck` by default), and then check on server startup if `shellcheck` executable is present. If not, we warn the user (from LSP) that they need to install it if they want linting. This warning will only be displayed once when the plugin is activated, e.g. each time they restart VSCode. I think this is not going to be too annoying.

**Comment by mlin** [comment]
@dinvlad the `WDL.Lint` module itself records whether shellcheck was available after it ran, so you may be able to reuse this (undocumented, but unlikely to change) flag:

https://github.com/chanzuckerberg/miniwdl/blob/b3c92007c1f8178dc99d124401f56e29f75d4efe/WDL/CLI.py#L127-L131

implementation:

https://github.com/chanzuckerberg/miniwdl/blob/b3c92007c1f8178dc99d124401f56e29f75d4efe/WDL/Lint.py#L752-L758

**Comment by dinvlad** [comment]
Hmm, seems like that requires a POSIX shell to be invoked, which may not always be true (e.g. ShellCheck supports Powershell as a client). It might be better to use [`shutil.which`](https://docs.python.org/dev/library/shutil.html) instead.

If we do, perhaps we could expose an API method like `WDL.Lint.linter_available()`?

**Comment by dinvlad** [comment]
I've just published an updated version of [WDL DevTools](https://marketplace.visualstudio.com/items?itemName=broadinstitute.wdl-devtools) extension that warns the user about ShellCheck once on startup.
