### ISSUE TITLE
'UnusedDeclaration' error for variables used in strings

### ISSUE THREAD

**Issue by infispiel** [chanzuckerberg/miniwdl#82]
Using an input in string interpolation is considered an unused declaration. A toy example follows:
```
version 1.0

workflow checkStringVariableUse {
  input {
    String inputString
  }
  String exampleUseCommand = "Hello ~{inputString}"

  call justRun {
    input:
      exampleUseCommand = exampleUseCommand
  }
}

task justRun {
  input {
    String exampleUseCommand
  }

  command <<<
    echo ~{exampleUseCommand}
  >>>
}
```
Example input is:
```
{
  "checkStringVariableUse.inputString": "world"
}
```
Warning returned by miniwdl is:
```
miniwdl_string_variables.wdl
    workflow checkStringVariableUse
        (Ln 5, Col 12) UnusedDeclaration, nothing references String inputString
        call justRun
    task justRun
```

**Comment by mlin** [comment]
@infispiel does Cromwell honor the ~{ } substitution in the declaration right-hand side, in addition to in the command? The spec actually needs some clarification here. The availability of ~{ } is discussed under the section about [task commands](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#command-section), but not under the section about [string interpolation](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#string-interpolation). Currently miniwdl recognizes ~{ } in the former only; if we change your example to `String exampleUseCommand = "Hello ${inputString}"` then we get the expected result.

**Comment by infispiel** [comment]
It is my understanding that `~{}` is preferred; I've opened an issue with the wdl repo asking for them to update the SPEC accordingly.

**Comment by pshapiro4broad** [comment]
It looks like the WDL spec isn't clear about the behavior of `~` outside of command blocks. Inside command blocks it's explicit, see [Expression Placeholders](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#expression-placeholders):

Command Body Style | Placeholder Style
-- | --
command { ... } | ~{} (preferred) or ${}
command <<< >>> | ~{} only

The outside command block case is called (String Interpolation)[https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#string-interpolation] but that doesn't even mention the `~{}` form.

**Comment by mlin** [comment]
Thanks! I’ll help drive that OpenWDL issue too. One of the goals of this project indeed is to elucidate areas like this where the spec can be improved. miniwdl does currently recognize the ~{} notation in task commands (in version 1.0+ WDL documents).

**Comment by mlin** [comment]
The upcoming point release will honor ~{} in these other string expressions, and we'll continue the discussion on https://github.com/openwdl/wdl/issues/285. Thanks!

**Comment by infispiel** [comment]
Great, thank you!
