### ISSUE TITLE
investigate Language Server Protocol

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/miniwdl#95]
https://microsoft.github.io/language-server-protocol/

**Comment by dinvlad** [comment]
We're currently exploring https://github.com/openlawlibrary/pygls SDK to develop LS in Python with MiniWDL. It seems rather straightforward, so I'll sketch a few ideas.

**Comment by mlin** [comment]
Terrific- I hadn't discovered that library, and one of my pending worries indeed was whether we were going to have to start on that piece from scratch. Will be in touch soon, cc @tjchen @bkmartinjr

**Comment by dinvlad** [comment]
One idea I'm particularly interested in is to implement a "debugger" of sorts, using [Command](https://microsoft.github.io/language-server-protocol/specification#command) extensibility mechanism in LSP.

This command (initiated by the client, but running on the server) will take `metadata.json` from a given workflow, parse it (along with all of the WDL documents in the workspace), and then [publish Diagnostics](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics) about the workflow. These diagnostics will be automatically picked up by any LSP-compliant client and highlight any issues with the workflow, like info about failed task call(s), insufficient memory (where possible to detect), etc.

So this provides a way to enable editor-agnostic debugging of WDL (in addition to full language support), with very minimal setup required for each editor client.

**Comment by dinvlad** [comment]
I implemented WDL parsing in https://github.com/broadinstitute/wdl-ide-vscode/blob/7a2f870312976f0758f3aa6c39716b3be2de3d9e/wdl-language-support/server/server.py#L36-L54

A few initial thoughts:

1) `SyntaxError` doesn't have a `.pos` field, and it only reports the position of the error
in its message (`.args[0]`), in the form `(<filename>) <cause> at line <line> col <column>`. I had to parse this message with a regex to extract the user-friendly cause, as well as the line and column. It would be helpful to add a dedicated `.__cause__.strerror` (like for `ImportError`) and `.pos` (like for `ValidationError` and `MultipleValidationErrors`).
<img width="349" alt="Screen Shot 2019-06-01 at 11 26 08 PM" src="https://user-images.githubusercontent.com/137337/58756340-bf553680-84c4-11e9-9535-b98d95ddfa83.png">

2) `ValidationError` and `MultipleValidationErrors` don't have a dedicated "cause" attribute (like `.__cause__.strerror` for `ImportError`), so I had to parse the "clean" cause from `.args[0]` as well.
<img width="367" alt="Screen Shot 2019-06-01 at 10 55 30 PM" src="https://user-images.githubusercontent.com/137337/58756347-df84f580-84c4-11e9-92de-838a268015fc.png">

3) `ImportError` doesn't have a `.pos` either, but neither does it report line/column in the message (`.args[0]`). As a result, I can't display to the user the exact location of the failed import. Instead, I had to put it at the very beginning of the file (line 1, col 1).
<img width="487" alt="Screen Shot 2019-06-01 at 10 55 11 PM" src="https://user-images.githubusercontent.com/137337/58756348-e6ac0380-84c4-11e9-888b-a0ec018c5198.png">

With these caveats, the error reporting looks quite good!

**Comment by mlin** [comment]
@dinvlad Sorry for the slow response -- I've been swamped for the last couple of weeks but finally getting it under control a bit :sweat_smile: 

(1, 3) I've just [merged a patch](https://github.com/chanzuckerberg/miniwdl/commit/e7af077f891c2dddf9c9c952e1fefcdde33b44d4) to propagate the source position for SyntaxError and ImportError.

(2) ValidationError isn't meant to be a container/wrapper for another error, but rather the base class; many other more-specific exception classes (e.g. NoSuchTask, StaticTypeMismatch, CircularDependencies) derive from it. So you could test for those before or instead of testing for ValidationError -- does that help? MultipleValidationErrors has an attribute `exceptions : List[ValidationError]` with the associated specific errors.

(4) I understand, refactoring the loader so that an already-memory-resident document source can use imports shouldn't be too difficult, provided the proper working directory is given. I [filed an issue](https://github.com/chanzuckerberg/miniwdl/issues/154) to follow up with a few thoughts about how we might do it.

Thank you for all of this great feedback, I'm really excited for the language server especially as I'm a VSCode user myself!!

**Comment by dinvlad** [comment]
Perfect, thanks @mlin !

The path for (1, 3) will help a lot!

Re (2), both `ValidationError` and `List[ValidationError]` are treated equally currently. We have to parse the string representation of the error (`str(e)`) to find the cause, like so:
```py
re.match("^\(.*\) (.*)", str(e)).group(1)
```
It would help if we just had a catch-all `.cause` attribute for those instead. However, the workaround is fine too, provided that the error message format doesn't change.

[Here](https://github.com/broadinstitute/wdl-ide/blob/c3770538e09cbd4409bc798606c2ba8c40ba4cdd/wdl-language-support/server/server.py#L87-L127)'s how all of these cases are handled right now. Once (1, 3) gets released, we'll only have to keep the logic for parsing out the cause (if there isn't a better way).

Any improvement on (4) would be much appreciated! Currently, we have to save the file in order for it to be re-validated. This is not a deal breaker, and validation is fast (thanks to MiniWDL optimizations I assume!). However, users who saw the preview already asked if it could validate "on the fly". I think given MiniWDL's speed, this would provide a very good experience (and even if there was ~1 sec of additional delay, it would still be ok).

To align it even further with the LSP spec, the server could keep track of which document URIs are "opened" on the client, and then provide their in-memory content for validation to MiniWDL, along with the URIs of the ones not opened. Maybe we could use
```py
WDL.parse_document(txt, files: Mapping[String, BaseIO] = [], path: List[str] = [], ...)
```
as an extension of `WDL.parse_document()`, and then pass through `files` any in-memory (or even local?) files that we'd like? I.e. `files` could consist of in-memory files constructed with `StringIO`. And the `path` argument would be used to "discover" URIs (both opened and closed), just like it does currently for `WDL.load()`.

@rexwangcc thoughts?

**Comment by mlin** [comment]
@dinvlad OK, I think I understand what you're getting at:

In https://github.com/chanzuckerberg/miniwdl/commit/b7f399b56ad2f01ed9867e6105c036a251c4ae73 I changed how the exception objects are initialized so that the filename/line/column is no longer textually prepended to the error message. Instead `str(exn)` will produce the error message alone, and tools like the miniwdl CLI and your language server can access and display the SourcePosition from the `pos` attribute when needed. This should eliminate the need for the regexp parsing, although on the downside it will also break it.

I got a simpler solution for the in-memory parsing, https://github.com/chanzuckerberg/miniwdl/commit/91293ea486f882cdc0c0ebb7b9ccfe23e3b5a063 simply adds an optional `source_text : str` argument to `WDL.load()`, if you supply that then it will use it instead of reading from the filename/URI. (The uri is still needed for resolving relative imports and filling in `SourcePosition.filename`) This will still read *imported* documents from disk though -- is that constraint suitable?

I plan to cut a new point release at the end of the week to include these changes.

A valuable next step for the wdl-ide will be to include `miniwdl check`'s lint *warnings* in addition to the parsing/typechecking *errors* you're getting now. Right now the API is undocumented (#78) but briefly, after successfully loading `doc : WDL.Document`, invoking `WDL.Lint.lint(doc).collect()` will return a list of triplets `(node : WDL.SourceNode, warning_class : str, message : str)` (each `SourceNode` having the `pos : SourcePosition` attribute). Note this will include lint warnings recursively for all imported documents too.

**Comment by dinvlad** [comment]
Perfect solutions for `pos` and `str(exn)`, looking forward to the release!

The linter also looks awesome, I’ll add warnings based on that!

Re `source_text`, that solves the immediate problem of displaying issues for the _currently active_ file. However, I think we could do even better, because LSP really expects clients to pass the content of all currently _open_ files to the language server (and to remove them from server “memory” when they’re closed by the client). This way, all unsaved changes in all currently open documents are taken into account. Otherwise, it becomes counter-intuitive when a user makes some edits to a file (e.g. a sub-workflow) without saving it, sees some issues, then switches over to a different file (which could be even the “main” file) and suddenly those issues disappear and everything “looks good”.

What I’d propose is a way to specify and resolve _multiple_ files from source. So we could still supply the main file, either by `uri` or `source_text`, and then in _addition_ to that supply dependencies through `path` or a new argument, like `dependent_text: List[str]`. Would it be possible to add such an argument?

**Comment by mlin** [comment]
OK, glad we're moving in the right direction :) I'll be making the new point release shortly. Let me try to take some time to study LSP more carefully so I can better understand the constraints and how to make the API convenient for them. My only concern so far is how to properly match up the path provided in the `import` statement, which might be a relative path, with something in the list of open files provided by the editor.

**Comment by dinvlad** [comment]
One possible solution is to pass both the URI and the content - e.g. we could pass a `Map[str, str]` which maps a file URI to its content. This way, MiniWDL can both resolve them through imports, and get access to the full content.

**Comment by mlin** [comment]
@dinvlad I'm closing this general 'investigate' ticket since you're already running with it so far :) I wrote #177 about providing source text for multiple files
